Add API tutorial
chainstack/docs pull request #273
Opened 2020-08-24 05:45 UTC by akegaviar

Added a short tutorial on how to create a consortium network and retrieve node
details through the API.

2020-08-24 16:10 UTC, easeev commented on docs/.vuepress/config.js
> +                    '/api/walkthrough-to-create-a-consortium-network-through-API',
Awful slug, probably should be just `/api/overview`

2020-08-24 16:27 UTC, CaJIbHuK requested changes

2020-08-24 16:27 UTC, CaJIbHuK commented on docs/api/walkthrough-to-create-a-consortium-network-through-API.md
> +export APIURL="https://api.dev.chainstack.com/v1"
I think it's better to parametrize to have `https://api.dev.chainstack.com/v1` in dev docs and `https://api.chainstack.com/v1` in prod docs. Similar to 
```
* <a :href="$themeConfig.apiDocsURL" target="_blank">API reference</a>
```

2020-08-24 23:36 UTC, akegaviar commented on docs/api/walkthrough-to-create-a-consortium-network-through-API.md
> +export APIURL="https://api.dev.chainstack.com/v1"
Good catch. Don't think we need to go into trouble parametrizing this, just need the proper base url for prop.

2020-08-25 05:33 UTC, CaJIbHuK approved these changes

2020-08-25 09:42 UTC, easeev commented on docs/.vuepress/config.js
> +                    '/platform/create-an-api-key',
Should be after settings as API key management is part of settings

2020-08-25 09:42 UTC, easeev commented on docs/api/README.md
> +* your [identities](/platform/manage-your-organization-identity).
It looks like we need `/glossary/identity`

2020-08-25 09:43 UTC, easeev commented on docs/.vuepress/config.js
> +                    '/api/quick-tutorial',
👍

2020-08-25 09:58 UTC, akegaviar commented on docs/api/README.md
> +* your [identities](/platform/manage-your-organization-identity).
done

2020-08-25 09:59 UTC, akegaviar commented on docs/.vuepress/config.js
> +                    '/platform/create-an-api-key',
done

2020-08-25 10:10 UTC, easeev commented on docs/api/quick-tutorial.md
> +	* [MultiChain round-robin](/blockchains/multichain#consensus) — `round-robin`.
```suggestion
	* [MultiChain Round-robin](/blockchains/multichain#consensus) — `round-robin`.
```

2020-08-25 10:10 UTC, easeev commented on docs/api/quick-tutorial.md
> +* NODE_NAME — any name you want to give to your first node deployed as part of the network.
```suggestion
* NODE_NAME — any name you want to give to your first peer node deployed as part of the network.
```

2020-08-25 10:13 UTC, easeev commented on docs/api/quick-tutorial.md
> +* LOCATION — choose the location for your node:
```suggestion
* LOCATION — choose the location for your network:
```

2020-08-25 10:14 UTC, easeev commented on docs/api/quick-tutorial.md
> +### Add a node to the network
```suggestion
### Add a peer node to the network
```

?

2020-08-25 10:17 UTC, akegaviar commented on docs/api/quick-tutorial.md
> +	* [MultiChain round-robin](/blockchains/multichain#consensus) — `round-robin`.
I think in this particular case it must be `round-robin`. While `Raft` and `IBFT` are consensus names, `round-robin` is a descriptive consensus name and must be lower case.

2020-08-25 12:14 UTC, easeev commented on docs/api/quick-tutorial.md
> +See also API reference: <a :href="$themeConfig.apiDocsURL + '#operation/createProject'" target="_blank">Create Project</a>.
```suggestion
See also API reference: <a :href="$themeConfig.apiDocsURL + '#operation/createProject'" target="_blank">Create project</a>.
```

?

2020-08-25 12:16 UTC, easeev commented on docs/api/quick-tutorial.md
> +* NODE_TYPE — `dedicated` is the only available option for consortium networks.
We kinda skip the explanation of why we also create a node with the network and why its role is `peer`

2020-08-25 12:16 UTC, easeev commented on docs/api/quick-tutorial.md
> +See also API reference: <a :href="$themeConfig.apiDocsURL + '#operation/createNetwork'" target="_blank">Create Network</a>.
```suggestion
See also API reference: <a :href="$themeConfig.apiDocsURL + '#operation/createNetwork'" target="_blank">Create network</a>.
```
?

2020-08-25 12:17 UTC, easeev commented on docs/api/quick-tutorial.md
> +See also API reference: <a :href="$themeConfig.apiDocsURL + '#operation/retrieveNode'" target="_blank">Retrieve Node</a>.
```suggestion
See also API reference: <a :href="$themeConfig.apiDocsURL + '#operation/retrieveNode'" target="_blank">Retrieve node</a>.
```
?

2020-08-26 01:50 UTC, akegaviar commented on docs/api/quick-tutorial.md
> +See also API reference: <a :href="$themeConfig.apiDocsURL + '#operation/createProject'" target="_blank">Create Project</a>.
No, because we are keeping the capitalization [Create Project](https://docs.dev.chainstack.com/api/reference/#operation/createProject) in the API reference. And we are keeping it there to identify `Project` as an object.

2020-08-26 01:50 UTC, akegaviar commented on docs/api/quick-tutorial.md
> +See also API reference: <a :href="$themeConfig.apiDocsURL + '#operation/createNetwork'" target="_blank">Create Network</a>.
Same as with `Project`

2020-08-26 01:50 UTC, akegaviar commented on docs/api/quick-tutorial.md
> +See also API reference: <a :href="$themeConfig.apiDocsURL + '#operation/retrieveNode'" target="_blank">Retrieve Node</a>.
Same as with `Project`

2020-08-26 02:01 UTC, akegaviar commented on docs/api/quick-tutorial.md
> +* NODE_TYPE — `dedicated` is the only available option for consortium networks.
Done

2020-08-26 04:32 UTC, easeev commented on docs/api/quick-tutorial.md
> +You create a network with one peer node and free service nodes.
```suggestion
You create a network with one peer node and service nodes.
```

2020-08-26 04:32 UTC, easeev commented on docs/api/quick-tutorial.md
> +The service nodes are read-only and are created automatically with no input from you.
```suggestion
The service nodes are created automatically with no input from you.
```

2020-08-26 04:33 UTC, easeev commented on docs/api/quick-tutorial.md
> +* NODE_ROLE — use the `peer` value for the role since you are providing node details for your peer node. The service nodes are created automatically with no input from you.
Probably redundant here

```suggestion
* NODE_ROLE — use the `peer` value for the role since you are providing node details for your peer node.
```

2020-08-26 05:24 UTC, easeev commented on docs/api/quick-tutorial.md
> +You create a network with one peer node and service nodes.
Should we have a link on `service nodes` to explain what's that? Same for `peer node` potentially

2020-08-26 05:54 UTC, akegaviar commented on docs/api/quick-tutorial.md
> +You create a network with one peer node and service nodes.
Yes, we should.

Committed.

2020-08-26 10:11 UTC, easeev commented on docs/glossary/service-node.md
> +A read-only node automatically deployed with your consortium network to provide consortium services.
```suggestion
A node deployed with your consortium network to provide network services.
```

2020-08-26 10:12 UTC, easeev commented on docs/glossary/peer-node.md
> +Your regular blockchain node that you deploy to interact with and be a part of a consortium network.
```suggestion
A node that you deploy to interact with and be a part of a blockchain network.
```

2020-08-26 10:17 UTC, merged