Add Chainstack 2.1.2 release notes retrospectively
chainstack/docs pull request #306
Opened 2020-11-10 13:40 UTC by neewy

2020-11-10 13:47 UTC, akegaviar reviewed
We don't do x.x.x version relnotes. We only do x.x versions.

And looking at the changes introduced, I am not sure why we should start now.

2020-11-12 06:03 UTC, CaJIbHuK commented
@neewy @easeev shall we close this PR?

2020-11-12 06:09 UTC, easeev commented
> We don't do x.x.x version relnotes. We only do x.x versions.

Well, if we look at https://docs.chainstack.com/release-notes, we definitely did release notes for x.x.x :)

>@neewy @easeev shall we close this PR?

I have no strong opinion on that, IMO it makes sense to publish release notes when we have something to say. In this case there's some substance so it's fine to keep them

2020-11-12 06:09 UTC, easeev commented on docs/release-notes.md
> +* Hyperledger Fabric Explorer being out of sync with the network state.
Perhaps we should rephrase to make it clear that only some explorers were out of sync and not all

2020-11-12 08:08 UTC, neewy commented on docs/release-notes.md
> +* Hyperledger Fabric Explorer being out of sync with the network state.
```suggestion
* Resolved an issue with some Hyperledger Fabric Explorers being out of sync with the network state.
```

2020-11-12 08:15 UTC, akegaviar requested changes

2020-11-12 08:15 UTC, akegaviar commented on docs/release-notes.md
> +* **Improved billing experience**. You can now reattempt past due payments through billing card change or directly in the activity log (where you can see more information attached to your billing eve
Change to **Billing**.  We put component name in bold and then expand on what's done. The component here is billing (also mentioned in previous releases)

2020-11-12 08:15 UTC, akegaviar commented on docs/release-notes.md
> +* **Improved billing experience**. You can now reattempt past due payments through billing card change or directly in the activity log (where you can see more information attached to your billing eve
Something like this:

```
You can now reattempt past due payments through billing card change or directly in the activity log. The activity log also provides more information on your billing events.
```

Please avoid brackets as much as possible.

2020-11-13 06:23 UTC, neewy commented on docs/release-notes.md
> +* **Improved billing experience**. You can now reattempt past due payments through billing card change or directly in the activity log (where you can see more information attached to your billing eve
```suggestion
* **Billing**. You can now reattempt past due payments through billing card change or directly in the activity log. The activity log also provides more information on your billing events. 
```

2020-11-13 06:25 UTC, akegaviar submitted a review, later dismissed

2020-11-16 05:13 UTC, neewy commented
I can't merge without second approve, whenever you have a sec @CaJIbHuK please check it 🙏🏻

2020-11-16 05:29 UTC, easeev commented on docs/release-notes.md
> +* Resolved an issue with some Hyperledger Fabric Explorers being out of sync with the network state.
BTW there's no such thing as "Hyperledger Fabric Explorer", there's "[Hyperledger Explorer](https://github.com/hyperledger/blockchain-explorer)" or perhaps "Hyperledger Fabric explorer" if you want to mention Fabric

2020-11-16 06:11 UTC, neewy commented on docs/release-notes.md
> +* Resolved an issue with some Hyperledger Fabric Explorers being out of sync with the network state.
```suggestion
* Resolved an issue with some Hyperledger Explorer instances in Fabric networks being out of sync with the blockchain state.
```

2020-11-16 07:50 UTC, easeev approved these changes
LGTM

2020-11-16 08:06 UTC, akegaviar approved these changes

2020-11-17 05:27 UTC, merged