Add HLF Chainstack release 2.2 changes + polish
chainstack/docs pull request #313
Opened 2021-01-11 06:36 UTC by akegaviar

Added glossary items: Fabric CA, Cryptogen
Added instructions on how to manage the identities
Changed instructions on how to connect to peer
Added VSCode instructions
Did other minor polishing

2021-01-11 07:14 UTC, CaJIbHuK commented on docs/operations/fabric/tools.md
> +1. Click **Provide certificate and private key files**.
btw, certificate and a private key also can be added by using json file that is exported together with cryptomaterials when user exports identity
![image](https://user-images.githubusercontent.com/18049710/104154047-f4da3980-53f4-11eb-9576-c339d7e22973.png)

2021-01-11 07:14 UTC, CaJIbHuK commented on docs/operations/fabric/tools.md
> +1. Browse to the JSON connection profile for your peer node that you exported earlier.
as far as I remember, I had some troubles with adding ordered by clicking `Add more JSON definitions`. I had to add it by clicking `Import Nodes` after adding peer.
![image](https://user-images.githubusercontent.com/18049710/104154240-7a5de980-53f5-11eb-9757-424439f429b2.png)

2021-01-11 07:14 UTC, CaJIbHuK commented on docs/operations/fabric/tools.md
> +1. Click **Add identity**.
maybe worth mentioning that customers can reuse previously added identity

2021-01-11 08:51 UTC, akegaviar commented on docs/operations/fabric/tools.md
> +1. Browse to the JSON connection profile for your peer node that you exported earlier.
Interesting, I just tested again and you are correct. I remember testing both scenarios and both worked, so I did the `Add more JSON definitions` for the docs as it was shorter.

Good comment. Changed to the one that is definitely working.

2021-01-11 08:51 UTC, akegaviar commented on docs/operations/fabric/tools.md
> +1. Click **Add identity**.
Good one, done with the new flow.

2021-01-11 08:52 UTC, akegaviar commented on docs/operations/fabric/tools.md
> +1. Click **Provide certificate and private key files**.
great, this certainly makes things easier. fixed

2021-01-11 09:25 UTC, CaJIbHuK submitted a review, later dismissed

2021-01-11 13:07 UTC, neewy reviewed
Let's discuss

2021-01-11 13:07 UTC, neewy commented on docs/operations/fabric/tools.md
> +1. Select your identity issued by [cryptogen](/glossary/cryptogen).
Probably we should reference here Admin identity, available in network details. Otherwise it's hard for a user to understand which identity is in use by their HLF network.
<img width="905" alt="Screenshot 2021-01-11 at 16 01 37" src="https://user-images.githubusercontent.com/11841667/104185730-69799c00-5426-11eb-9666-3d6abaff8b58.png">

2021-01-11 13:07 UTC, neewy commented on docs/operations/fabric/tools.md
> +1. Click the orderer node that you added and select the wallet and the identity that you created when setting up the peer node.
> the identity that you created when setting up the peer node.

I got lost here, when setting up a peer node in Chainstack or in VS Code? Maybe we can paraphrase that for clarity

2021-01-11 13:07 UTC, neewy commented on docs/platform/manage-your-organization-identity.md
> +You can only delete an identity issuer after deleting the associated network.
We should probably mention in our docs what an identity issuer is and what kind of issuer<>network association is possible

2021-01-11 13:08 UTC, neewy commented on docs/operations/fabric/tools.md
> +* MSP_ID — the ID of your organization. To get the ID, open the peer connection profile you exported eariler and copy the `msp_id` value.
Outdated, sorry.

2021-01-11 13:08 UTC, neewy commented on docs/operations/fabric/tools.md
> +This will export the peer connection profile in JSON.
Probably outdated

2021-01-18 06:59 UTC, neewy commented
Also, I haven't found a section explaining how to create an identity issuer

2021-01-18 07:13 UTC, akegaviar commented on docs/operations/fabric/tools.md
> +1. Click the orderer node that you added and select the wallet and the identity that you created when setting up the peer node.
Did you get lost when going through the instructions live in VS Code? Because this is the only option in VS Code that you can do and it's really difficult to confuse with anything else.

The entire set of instructions is for VS Code, and when you click the node VS Code, selecting the wallet and the identity are the only options there.

2021-01-18 07:29 UTC, akegaviar commented on docs/operations/fabric/tools.md
> +1. Select your identity issued by [cryptogen](/glossary/cryptogen).
Good point. FIxed.

2021-01-18 08:08 UTC, akegaviar commented
> Also, I haven't found a section explaining how to create an identity issuer

Done.

2021-01-18 08:18 UTC, akegaviar commented on docs/platform/manage-your-organization-identity.md
> +You can only delete an identity issuer after deleting the associated network.
Done

2021-01-18 12:47 UTC, neewy requested changes
What's missing:
- view identity issuer (we can check details like certificate details for CA certificate, creation date, and configuration mode)
- view identity 
- mention that by default we have Corda Network & Corda Pre-Production Network in the list of identity issuers
- when an invited member add their peer to a fabric network they'd have to deploy a identity issuer first

2021-01-18 12:47 UTC, neewy commented on docs/platform/manage-your-organization-identity.md
> +This will generate an identity issuer.
```suggestion
This will add an identity issuer, and precreate an Admin identity for Fabric networks.
```

2021-01-18 12:47 UTC, neewy commented on docs/platform/manage-your-organization-identity.md
> +You can only delete an identity after deleting its identity issuer.
```suggestion
You can only delete an identity after deleting its issuer.
```

2021-01-18 12:47 UTC, neewy commented on docs/platform/manage-your-organization-identity.md
> +This will irrevocably delete the identity issuer private key and certificate files.
This will also delete an admin identity, issued by cryptogen. We precreate this admin identity when we add an identity issuer.

2021-01-18 12:47 UTC, neewy commented on docs/operations/fabric/tools.md
> +This will export two files:
```suggestion
This will export a ZIP archive, containing:
```

2021-01-19 07:49 UTC, akegaviar commented on docs/operations/fabric/tools.md
> +This will export two files:
Done

2021-01-19 07:51 UTC, akegaviar commented on docs/platform/manage-your-organization-identity.md
> +This will generate an identity issuer.
Done

2021-01-19 07:51 UTC, akegaviar commented on docs/platform/manage-your-organization-identity.md
> +You can only delete an identity after deleting its identity issuer.
done

2021-01-19 07:51 UTC, akegaviar commented on docs/platform/manage-your-organization-identity.md
> +This will irrevocably delete the identity issuer private key and certificate files.
done

2021-01-19 07:57 UTC, akegaviar commented
> view identity issuer (we can check details like certificate details for CA certificate, creation date, and configuration mode)

Done

> view identity

Done

> mention that by default we have Corda Network & Corda Pre-Production Network in the list of identity issuers

I don't think we should do this as these are third-party services and them existing in the UI doesn't change much for the end user (eg when compared to fabric)

> when an invited member add their peer to a fabric network they'd have to deploy a identity issuer first

Done

> identity issuer glossary definition

Done

2021-01-19 08:07 UTC, neewy approved these changes

2021-01-19 08:07 UTC, neewy commented on docs/platform/manage-your-organization-identity.md
> +This will irrevocably delete the both the identity and the identity issuer private keys and certificate files.
the admin identity probably?

2021-01-20 06:46 UTC, easeev commented on docs/operations/fabric/tools.md
> +1. Click the orderer node that you added and select the wallet and the identity that you created when setting up the peer node.
BTW I'm concerned about using the same Admin identity to access the orderer. It works in case if it's the first organization doing the setup since it owns the orderer. What about 2nd+ organizations? I assume it doesn't have access to the orderer

cc @CaJIbHuK

2021-01-20 06:48 UTC, CaJIbHuK commented on docs/operations/fabric/tools.md
> +1. Click the orderer node that you added and select the wallet and the identity that you created when setting up the peer node.
> It works in case if it's the first organization doing the setup since it owns the ordered.

No, it doesn't owns the ordered. Orderer has different set of certs

This scenario was tested for multiple orgs. This is what I got from rocket chat

2021-01-20 06:51 UTC, CaJIbHuK commented on docs/operations/fabric/tools.md
> +1. Click the orderer node that you added and select the wallet and the identity that you created when setting up the peer node.
https://chat.hyperledger.org/channel/fabric-questions?msg=CCvCgHGKeQAMasKWW

2021-01-21 05:48 UTC, CaJIbHuK approved these changes

2021-01-21 05:48 UTC, CaJIbHuK commented on docs/operations/fabric/tools.md
> +1. Click the orderer node that you added and select the wallet and the identity that you created when setting up the peer node.
Also, I think it will be good if we explain how to use connection-profile file that can be exported from network details modal. You can create `fabric gateway` from it in VS Code, which will give you an ability to call installed chaincode directly from the VS Code.

2021-01-21 05:50 UTC, easeev commented
>Also, I think it will be good if we explain how to use connection-profile file that can be exported from network details modal. You can create fabric gateway from it in VS Code, which will give you an ability to call installed chaincode directly from the VS Code.

You can also generate it from the existing Fabric environment. I tried and it works

![image](https://user-images.githubusercontent.com/14873170/105285554-9a5c8c80-5bef-11eb-9ef9-59fe7908bbed.png)

2021-01-21 07:57 UTC, akegaviar commented
great stuff, added the gateway instructions.

2021-01-21 12:30 UTC, CaJIbHuK commented on docs/operations/fabric/tools.md
> +This will export two files:
@akegaviar Looks like you haven't pushed changes

2021-01-21 12:39 UTC, neewy commented
@akegaviar please address this comment and we can merge this PR
![Screenshot 2021-01-21 at 15 38 34](https://user-images.githubusercontent.com/11841667/105352259-ba477c80-5bfe-11eb-91a8-ee5c4acfdf17.png)

2021-01-21 12:49 UTC, akegaviar commented on docs/operations/fabric/tools.md
> +This will export two files:
Good catch, pushed now. Thanks!

2021-01-21 12:50 UTC, neewy approved these changes

2021-01-21 13:04 UTC, CaJIbHuK commented on docs/platform/manage-your-organization-identity.md
> +This will irrevocably delete the both the identity and the identity issuer private keys and certificate files.
@akegaviar

2021-01-21 13:04 UTC, CaJIbHuK approved these changes

2021-01-21 15:46 UTC, easeev approved these changes
LGTM

2021-01-21 16:20 UTC, merged