Add private hosting + polish
chainstack/docs pull request #314
Opened 2021-01-18 02:04 UTC by akegaviar

Added private hosting changes.
Did some polishing of the existing docs.

2021-01-18 04:27 UTC, easeev commented on docs/.vuepress/config.js
>                      '/platform/manage-your-organization-identity',
Why not identities?

2021-01-18 04:27 UTC, easeev commented on docs/.vuepress/config.js
> +                    '/platform/manage-your-organization-integration',
Why not organizations?

2021-01-18 04:32 UTC, easeev commented on docs/platform/manage-your-organization-integration.md
> +You can add [Amazon Elastic Kubernetes Service (EKS)](https://aws.amazon.com/eks/) or a self-managed Kubernetes cluster as an integration to deploy your nodes and networks to it.
If we mention options that are not available yet I suggest to include other options in clouds as well (GKE, AKS)

2021-01-18 04:35 UTC, easeev commented on docs/platform/supported-hosting-options.md
> +* Chainstack-provided — deployment to cloud providers. See [Supported cloud providers](/platform/supported-cloud-hosting-providers).
I'd rephrase somehow to explain that this option is built-in in Chainstack and nodes are being deployed to the infrastructure that we manage/maintain/etc

2021-01-18 04:36 UTC, easeev commented on docs/platform/supported-hosting-options.md
> +* Private — deployment to a Kubernetes cluster. See [Manage your organization's integration](/platform/manage-your-organization-integration).
Here I'd explain that this option is about deploying into the infrastructure that you own (without mentioning Kubernetes here)

2021-01-18 05:23 UTC, akegaviar commented on docs/.vuepress/config.js
>                      '/platform/manage-your-organization-identity',
Done

2021-01-18 05:23 UTC, akegaviar commented on docs/.vuepress/config.js
> +                    '/platform/manage-your-organization-integration',
Done

2021-01-18 05:23 UTC, akegaviar commented on docs/platform/manage-your-organization-integration.md
> +You can add [Amazon Elastic Kubernetes Service (EKS)](https://aws.amazon.com/eks/) or a self-managed Kubernetes cluster as an integration to deploy your nodes and networks to it.
Done

2021-01-18 05:24 UTC, akegaviar commented on docs/platform/supported-hosting-options.md
> +* Chainstack-provided — deployment to cloud providers. See [Supported cloud providers](/platform/supported-cloud-hosting-providers).
Done

2021-01-18 05:24 UTC, akegaviar commented on docs/platform/supported-hosting-options.md
> +* Private — deployment to a Kubernetes cluster. See [Manage your organization's integration](/platform/manage-your-organization-integration).
Done

2021-01-18 09:35 UTC, neewy reviewed
That is a quick review. I'll check the flow for private hosting and will let you know again.

2021-01-18 09:35 UTC, neewy commented on docs/platform/manage-your-organizations-integrations.md
> +1. Provide any domain name for the deployment. This domain name will be a part of your node's endpoint URL.
```suggestion
1. Provide a domain name. This domain name will be used as a root domain name, and the nodes you deploy will be accessible via generated subdomain endpoint URL. 
```

2021-01-18 09:35 UTC, neewy commented on docs/platform/manage-your-organizations-integrations.md
> +Once the integration is validated, you can use it to deploy your nodes and networks.
Should we tell how long this takes on average?

2021-01-18 09:35 UTC, neewy commented on docs/platform/manage-your-organizations-integrations.md
> +Once the integration is validated, you can use it to deploy your nodes and networks.
```suggestion
Once the integration is validated, which takes 5 minutes on average, you can use it to deploy your nodes and networks.
```

2021-01-18 09:35 UTC, neewy commented on docs/platform/manage-your-organizations-integrations.md
> +1. Click **Edit** > **Delete**.
We need to tell that deletion takes time and probably tell that we will delete all Chainstack-added pods, except for cert-manager, installed through helm

2021-01-18 09:47 UTC, akegaviar commented on docs/platform/deploy-a-consortium-network.md
> +1. Under **Identity issuer**, select **Cryptogen**.
It's in a different PR.

2021-01-18 09:53 UTC, akegaviar commented on docs/platform/manage-your-organizations-integrations.md
> +1. Provide the access key and secret of the user you have specifically created for the Chainstack integration.
No, it's under `[Manage your organization's integrations](/platform/manage-your-organizations-integrations)`

2021-01-18 09:54 UTC, akegaviar commented on docs/platform/manage-your-organizations-integrations.md
> +Once the integration is validated, you can use it to deploy your nodes and networks.
I don't remember it taking too much time, so I wouldn't.

2021-01-18 09:54 UTC, akegaviar commented on docs/platform/manage-your-organizations-integrations.md
> +Once the integration is validated, you can use it to deploy your nodes and networks.
I'd rather not.

2021-01-18 10:13 UTC, akegaviar commented on docs/platform/manage-your-organizations-integrations.md
> +1. Click **Edit** > **Delete**.
It's relatively fast, so we don't need to complicate the instructions with the time.

2021-01-18 12:59 UTC, neewy requested changes
What's missing:
- mention that Integrations are available on Business and Enterprise plans
- a stopped node deployed in private hosting will not incur maintenance costs  
- to deploy a consortium that is spanning across different hostings a network creator has to be on enterprise plan 

Please also mention where are the requirements for AWS user with programmatic access that we use during integration wizard.

2021-01-18 12:59 UTC, neewy commented on docs/platform/manage-your-organizations-integrations.md
> +1. Provide the access key and secret of the user you have specifically created for the Chainstack integration.
It says
> For instructions on how to set up your Amazon EKS cluster for Chainstack integration

But it does not mention that this KB article explains also IAM roles for a user with programmatic access. This would make me confused. I'd suggest mentioning the topics covered in the KB article, which includes setting up an AWS IAM user for Chainstack Integration, Node Groups sizing for supported protocols, and EKS cluster setup.

2021-01-18 12:59 UTC, neewy commented on docs/platform/manage-your-organizations-integrations.md
> +1. Provide any domain name for the deployment. This domain name will be a part of your node's endpoint URL.
Why did you ignore this suggestion?

2021-01-18 13:08 UTC, neewy commented
@easeev I think that we haven't discussed this point and it wasn't implemented yet: 

> a stopped node deployed in private hosting will not incur maintenance costs


Let's discuss that and I will tell Ake what to put in a "stop a node" section

2021-01-18 13:55 UTC, neewy commented
We also need to mention customer responsibilities for EKS cluster and resource sizing somewhere, i.e. a customer has to make sure their EKS cluster is operational, they set up snapshots for their storage so that they can recover in case of any accident in AWS, and that IAM user and k8s RBAC rights remain unaffected (otherwise their integration becomes unstable). As for resource sizing please refer to Avi's doc, Node Group section.

2021-01-18 14:04 UTC, neewy commented
@akegaviar besides IAM user, there are other prerequisites such as Kubernetes version, etc. Maybe we can add a section in our "Integration" section called "Prerequisites"?

2021-01-19 03:39 UTC, akegaviar commented on docs/platform/manage-your-organizations-integrations.md
> +1. Provide the access key and secret of the user you have specifically created for the Chainstack integration.
Okay, added.

2021-01-19 03:40 UTC, akegaviar commented
> mention that Integrations are available on Business and Enterprise plans

Done

> a stopped node deployed in private hosting will not incur maintenance costs

Pending your discussion

> to deploy a consortium that is spanning across different hostings a network creator has to be on enterprise plan

Done

> Please also mention where the requirements are for AWS user with programmatic access that we use during integration wizard.

Done

2021-01-19 03:41 UTC, akegaviar commented
> We also need to mention customer responsibilities for EKS cluster and resource sizing somewhere, i.e. a customer has to make sure their EKS cluster is operational, they set up snapshots for their storage so that they can recover in case of any accident in AWS, and that IAM user and k8s RBAC rights remain unaffected (otherwise their integration becomes unstable). As for resource sizing please refer to Avi's doc, Node Group section.

Done in the KB article

2021-01-19 03:42 UTC, akegaviar commented
> besides IAM user, there are other prerequisites such as Kubernetes version, etc. Maybe we can add a section in our "Integration" section called "Prerequisites"?

I really want to keep this in the KB and not in the docs. It's all in the KB article.

2021-01-19 06:10 UTC, neewy commented
> a stopped node deployed in private hosting will not incur maintenance costs

Approved, let's add this to the docs please.

2021-01-21 01:51 UTC, akegaviar commented
> Approved, let's add this to the docs please.

Done

2021-01-21 07:12 UTC, neewy approved these changes

2021-01-21 07:12 UTC, neewy commented on docs/platform/manage-your-organizations-identities.md
> +1. Navigate to <a href="https://console.chainstack.com/vault" target="_blank">your vault</a> and select the identity to export.
why href links?

2021-01-21 12:38 UTC, CaJIbHuK requested changes

2021-01-21 12:38 UTC, CaJIbHuK commented on docs/platform/deploy-a-consortium-network.md
> +	* For private hosting, select an integration. See [Manage your organization's integrations](/platform/manage-your-organizations-integrations).
```suggestion
	* For private hosting, select or add an integration. See [Manage your organization's integrations](/platform/manage-your-organizations-integrations).
```

2021-01-21 12:38 UTC, CaJIbHuK commented on docs/platform/join-a-public-network.md
> +	* For private hosting, select an integration. See [Manage your organization's integrations](/platform/manage-your-organizations-integrations).
```suggestion
	* For private hosting, select or add an integration. See [Manage your organization's integrations](/platform/manage-your-organizations-integrations).
```

2021-01-21 12:53 UTC, akegaviar commented on docs/platform/manage-your-organizations-identities.md
> +1. Navigate to <a href="https://console.chainstack.com/vault" target="_blank">your vault</a> and select the identity to export.
href links are for chainstack-resources

2021-01-21 12:55 UTC, akegaviar commented on docs/platform/manage-your-organizations-integrations.md
> +* [Azure Kubernetes Service (AKS)](https://azure.microsoft.com/en-us/services/kubernetes-service/)
@easeev ?

2021-01-21 12:59 UTC, neewy submitted a review, later dismissed

2021-01-21 13:12 UTC, CaJIbHuK approved these changes

2021-01-21 15:51 UTC, easeev commented on docs/platform/manage-your-organizations-integrations.md
> +* [Azure Kubernetes Service (AKS)](https://azure.microsoft.com/en-us/services/kubernetes-service/)
I think the current list is good enough for now

2021-01-21 15:57 UTC, easeev commented on docs/.vuepress/config.js
> +                    '/platform/view-your-organizations-vault',
Does `organizations-xxx` sound a bit odd clunky to me only?

Isn't this more consistent?
- Organization identities
- Organization integrations
- Organization vault
- User settings

2021-01-21 16:06 UTC, easeev commented on docs/platform/deploy-a-consortium-network.md
> +Deployment of multicloud and hybrid hosting networks is available starting from the Enterprise <a href="https://chainstack.com/pricing/" target="_blank">subscription plan</a>.
We should be consistent with terminology on the website, in the platform, in the docs

```suggestion
Deployment of cross-cloud, cross-region and hybrid networks is available starting from the Enterprise <a href="https://chainstack.com/pricing/" target="_blank">subscription plan</a>.
```

2021-01-21 16:09 UTC, easeev commented on docs/platform/deploy-a-consortium-network.md
> +	* For Chainstack hosting, select a cloud provider.
Here and below IMO should be

```suggestion
	* For Chainstack hosting, select a cloud provider and a region.
```

2021-01-21 16:10 UTC, easeev commented on docs/platform/stop-or-start-a-node.md
> +A stopped node in Chainstack-provided hosting retains its states and does not incur metered compute costs but does incur storage costs.
Why "states" not "state"?

2021-01-21 16:11 UTC, easeev commented on docs/.vuepress/config.js
> +                    '/platform/view-your-organizations-vault',
No strong opinion here, up to @akegaviar to decide

2021-01-21 16:13 UTC, easeev requested changes
Minor changes required

2021-01-21 23:17 UTC, akegaviar commented on docs/.vuepress/config.js
> +                    '/platform/view-your-organizations-vault',
Fixed

2021-01-21 23:17 UTC, akegaviar commented on docs/platform/stop-or-start-a-node.md
> +A stopped node in Chainstack-provided hosting retains its states and does not incur metered compute costs but does incur storage costs.
Fixed

2021-01-22 04:43 UTC, easeev commented on docs/platform/create-a-project.md
> +## Public chain project
Why "Public chain project" whereas the header above is "Create a consortium project"?

2021-01-22 05:11 UTC, akegaviar commented on docs/platform/create-a-project.md
> +## Public chain project
There are two sections. One for consortium, one for public chain.

The word `Create` is missing, hence the confuson.

Fixed.

2021-01-22 05:13 UTC, easeev approved these changes
LGTM

2021-01-22 05:58 UTC, merged