Add Chainstack v2.2 release notes
chainstack/docs pull request #315
Opened 2021-01-18 14:17 UTC by neewy

- Private hosting
- AWS US East region
- Identity issuers

2021-01-18 23:09 UTC, akegaviar commented on docs/release-notes.md
> +* **AWS US East region**. You can now deploy your nodes and networks in the <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regio
Please spell out the full name for AWS.

2021-01-18 23:09 UTC, akegaviar commented on docs/release-notes.md
> +* **AWS US East region**. You can now deploy your nodes and networks in the <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regio
Links to non-Chainstack resources must be in markdown format.

2021-01-21 13:13 UTC, CaJIbHuK approved these changes

2021-01-21 16:15 UTC, easeev commented on docs/release-notes.md
> +*January 25, 2021*
Apparently

```suggestion
*January 22, 2021*
```

2021-01-21 16:17 UTC, easeev commented on docs/release-notes.md
> +* **Private hosting**. Connect your Chainstack organization to Amazon Elastic Kubernetes Service (EKS), and use your EKS clusters to host your blockchain nodes and networks.
"Connect your Chainstack organization to Amazon Elastic Kubernetes Service" sounds weird

```suggestion
* **Private hosting**. You can now your own Amazon Elastic Kubernetes Service (EKS) infrastructure to deploy blockchain nodes and networks on Chainstack.
```

2021-01-21 16:18 UTC, easeev requested changes
Minor changes required

2021-01-22 05:04 UTC, easeev approved these changes
LGTM

2021-01-22 05:41 UTC, akegaviar approved these changes

2021-01-22 05:56 UTC, merged