Add BSC docs
chainstack/docs pull request #330
Opened 2021-04-01 07:05 UTC by akegaviar

2021-04-01 07:11 UTC, easeev commented on docs/.vuepress/config.js
> +                            '/operations/binance/',
I suggest `/bsc` handle instead of `/binance` to avoid any confusion with Binance Chain

2021-04-01 08:00 UTC, akegaviar commented on docs/.vuepress/config.js
> +                            '/operations/binance/',
Done

2021-04-05 14:02 UTC, neewy requested changes
Amazing tutorial! Having in mind our shared nodes service changes, should we mention it for BSC too?

2021-04-05 14:02 UTC, neewy commented on docs/operations/bsc/types.md
> +* Shared — the node resources are shared with other platform users.
We should mention included JSON-RPC request volumes here

2021-04-19 08:41 UTC, CaJIbHuK commented
@akegaviar @easeev what shall we do with this PR?

2021-04-19 08:48 UTC, easeev submitted a review, later dismissed
LGTM (after rebase)

2021-04-20 15:22 UTC, easeev approved these changes
LGTM

2021-04-21 05:00 UTC, merged