Add token-based auth, command switcher, reorder protocols
chainstack/docs pull request #358
Opened 2021-08-09 04:51 UTC by akegaviar

Added token-based access instructions.
Added a command switcher to accomodate token-based and basic auth.
Reordered protcols for consistency.

2021-08-09 04:53 UTC, akegaviar commented
@neewy what will the graphql endpoint look like? I didn't find it in the designs and for now I put:

```
https://nd-123-456-789.p2pify.com/graphql/alpha-beta-gamma-delta-epsilon-zeta
```

2021-08-11 11:40 UTC, akegaviar commented
> @akegaviar can you check on a dedicated node on dev?
Done and fixed in the docs now

2021-08-14 16:45 UTC, easeev commented on docs/operations/bsc/tools.md
> +geth attach ENDPOINT/TOKEN
1. In the current implementation default endpoint already contains a token, so there's no need to specify it separately
2. We agreed to use "key" instead of "token" as "token" is generally used in another context. It would be incorrect to say "key-based authentication" either (as it is used in SSH key context) so a relatively good option is something like "URL key authentication"
3. Also the naming here should be somewhat related to what we have in the platform (we don't talk about "token" or "basic authentication"): we have "Access and credentials" and "Password-protected access and credentials". Or we should explain this in the beginning somehow

2021-08-14 16:46 UTC, easeev commented on docs/operations/bsc/tools.md
> +geth attach USERNAME:PASSWORD@ENDPOINT
Looks like now it will be `username:password@wss://nd-123-456-789.p2pify.com` which will not work

2021-08-14 16:47 UTC, easeev commented on docs/operations/bsc/tools.md
> +      'GRAPHQL_ENDPOINT/TOKEN',
Same as above, default GraphQL endpoint includes "token" by default

2021-08-14 16:48 UTC, easeev commented on docs/operations/bsc/tools.md
> +web3 = Web3(Web3.HTTPProvider('https://%s:%s@%s'% ("USERNAME", "PASSWORD", "ENDPOINT")))
`https://username:password@https://nd-123-456-789.p2pify.com`

2021-08-14 16:52 UTC, easeev commented on docs/tutorials/bsc/bep-1155-contract-with-truffle-and-openzeppelin.md
> +* ENDPOINT — your Binance Smart Chain node endpoint. The format is token-based: `https://nd-123-456-789.p2pify.com/alpha-beta-gamma-delta-epsilon-zeta` or basic authentication:`https://user-name:pass
I think we can keep the default endpoint (which is key-based) in all tutorials and omit basic auth one

2021-08-14 16:52 UTC, easeev requested changes
Address comments

2021-08-15 05:42 UTC, akegaviar commented on docs/tutorials/bsc/bep-1155-contract-with-truffle-and-openzeppelin.md
> +* ENDPOINT — your Binance Smart Chain node endpoint. The format is token-based: `https://nd-123-456-789.p2pify.com/alpha-beta-gamma-delta-epsilon-zeta` or basic authentication:`https://user-name:pass
Done

2021-08-15 05:43 UTC, akegaviar commented on docs/operations/bsc/tools.md
> +web3 = Web3(Web3.HTTPProvider('https://%s:%s@%s'% ("USERNAME", "PASSWORD", "ENDPOINT")))
Fixed

2021-08-15 05:43 UTC, akegaviar commented on docs/operations/bsc/tools.md
> +      'GRAPHQL_ENDPOINT/TOKEN',
Fixed

2021-08-15 05:43 UTC, akegaviar commented on docs/operations/bsc/tools.md
> +geth attach USERNAME:PASSWORD@ENDPOINT
Fixed

2021-08-15 05:43 UTC, akegaviar commented on docs/operations/bsc/tools.md
> +geth attach ENDPOINT/TOKEN
Changed

2021-08-15 05:43 UTC, akegaviar commented
Comments addressed

2021-08-16 01:23 UTC, easeev commented on docs/operations/bsc/tools.md
> +geth attach https://nd-123-456-789.p2pify.com/a1b2c3d4e5f6g7h8i9j1k2l3m4n5o6p7
Can be hex only

```
$ echo -n key | md5sum
3c6e0b8a9c15224a8228b9a98ca1531d  -
```

2021-08-16 01:24 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +A HTTPS or WSS endpoint with password protection.
We need to explain that we use Basic Authentication

2021-08-16 01:26 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +To use the password-protected endpoint, you must provide the username and password in the HTTPS or WSS header.
1. In the example below, we don't provide username/password in the _header_ but rather in the URL
2. It would be good to explain briefly how to pass the username/password in the header as one of the options
3. For WSS you can't pass username/password in the header https://stackoverflow.com/a/41521871/11765084

2021-08-16 01:28 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +A HTTPS or WSS endpoint with URL key authentication.
Can be also GraphQL for instance so I'd rather just say "An API endpoint with ..." or something similar

2021-08-16 01:30 UTC, easeev commented on docs/tutorials/bsc/bep-1155-contract-with-truffle-and-openzeppelin.md
> +* ENDPOINT — your Binance Smart Chain node endpoint. The format is `https://nd-123-456-789.p2pify.com/a1b2c3d4e5f6g7h8i9j1k2l3m4n5o6p7`. See also [View node access and credentials](/platform/view-nod
"your Binance Smart Chain _HTTPS_ node endpoint"?

2021-08-16 01:32 UTC, easeev commented on docs/tutorials/ethereum/asset-tokenization-with-embark.md
> +    * RPC_ENDPOINT — your Ropsten node RPC endpoint. The format is `nd-123-456-789.p2pify.com/a1b2c3d4e5f6g7h8i9j1k2l3m4n5o6p7`. See also [View node access and credentials](/platform/view-node-access
"your Ropsten node endpoint"? As we don't mention RPC anywhere now

2021-08-16 01:41 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +## Public nodes
"Public chain nodes"?

2021-08-16 06:27 UTC, akegaviar commented on docs/operations/bsc/tools.md
> +geth attach https://nd-123-456-789.p2pify.com/a1b2c3d4e5f6g7h8i9j1k2l3m4n5o6p7
fixed

2021-08-16 06:28 UTC, akegaviar commented on docs/platform/view-node-access-and-credentials.md
> +A HTTPS or WSS endpoint with password protection.
Done

2021-08-16 06:28 UTC, akegaviar commented on docs/platform/view-node-access-and-credentials.md
> +To use the password-protected endpoint, you must provide the username and password in the HTTPS or WSS header.
Done

2021-08-16 06:28 UTC, akegaviar commented on docs/platform/view-node-access-and-credentials.md
> +A HTTPS or WSS endpoint with URL key authentication.
Done

2021-08-16 06:28 UTC, akegaviar commented on docs/tutorials/bsc/bep-1155-contract-with-truffle-and-openzeppelin.md
> +* ENDPOINT — your Binance Smart Chain node endpoint. The format is `https://nd-123-456-789.p2pify.com/a1b2c3d4e5f6g7h8i9j1k2l3m4n5o6p7`. See also [View node access and credentials](/platform/view-nod
Done

2021-08-16 06:28 UTC, akegaviar commented on docs/tutorials/ethereum/asset-tokenization-with-embark.md
> +    * RPC_ENDPOINT — your Ropsten node RPC endpoint. The format is `nd-123-456-789.p2pify.com/a1b2c3d4e5f6g7h8i9j1k2l3m4n5o6p7`. See also [View node access and credentials](/platform/view-node-access
Done

2021-08-16 06:28 UTC, akegaviar commented on docs/platform/view-node-access-and-credentials.md
> +## Public nodes
Done

2021-08-16 07:10 UTC, neewy approved these changes

2021-08-16 11:45 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +An endpoint.
```suggestion
An endpoint with key authentication in the URL.
```

2021-08-16 11:45 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +An endpoint with basic authenticatiom.
```suggestion
An endpoint with basic authentication.
```

2021-08-16 11:47 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +To use the endpoint with basic authentication, you must provide the username and password:
```suggestion
To use the endpoint with Basic Authentication, you must provide the username and password in the URL:
```

2021-08-16 11:47 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +You can also pass the username in the HTTP header:
```suggestion
You can also pass the username and password in the HTTP header:
```

2021-08-16 11:48 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +    -H 'Accept:application/json' \
```suggestion
    -H 'Accept: application/json' \
```

2021-08-16 11:48 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +    -H 'Authorization:Basic BASE64_STRING' \
```suggestion
    -H 'Authorization: Basic BASE64_STRING' \
```

2021-08-16 11:55 UTC, easeev commented on docs/operations/polygon/tools.md
> +* HOSTNAME — your node hostname.
Maybe
```suggestion
* HOSTNAME — your node HTTPS endpoint hostname.
```

2021-08-16 11:55 UTC, easeev commented on docs/operations/polygon/tools.md
> +* HOSTNAME — your node WSS hostname.
And
```suggestion
* HOSTNAME — your node WSS endpoint hostname.
```

2021-08-16 11:57 UTC, easeev commented on docs/operations/ethereum/tools.md
> +* HOSTNAME — your node hostname.
Same here
```suggestion
* HOSTNAME — your node HTTPS endpoint hostname.
```

2021-08-16 16:58 UTC, easeev commented on docs/platform/view-node-access-and-credentials.md
> +## Public chain nodes
And Quorum

BTW we need to adjust the docs for Quorum as well

2021-08-17 04:35 UTC, akegaviar commented on docs/platform/view-node-access-and-credentials.md
> +## Public chain nodes
Done

2021-08-17 05:13 UTC, easeev commented on docs/operations/quorum/tools.md
> +* ENDPOINT — your Quorum node RPC endpoint. The format is `https://user-name:pass-word-pass-word-pass-word@nd-123-456-789.p2pify.com`. See [View node access and credentials](/platform/view-node-acces
Should we use a key-protected endpoint by default here?

2021-08-17 05:13 UTC, easeev commented on docs/operations/quorum/tools.md
> +* ENDPOINT — your Quorum node RPC endpoint. The format is `https://user-name:pass-word-pass-word-pass-word@nd-123-456-789.p2pify.com`. See [View node access and credentials](/platform/view-node-acces
Or have a switch like everywhere else

2021-08-17 05:14 UTC, easeev commented on docs/operations/quorum/tools.md
> +* ENDPOINT — your node HTTPS endpoint.
Endpoint should come first (I fixed it in a few occasions in the recent commit) as it's logical: endpoint -> username/password and not vice versa

2021-08-17 05:15 UTC, easeev commented on docs/operations/bitcoin/tools.md
> +curl https://nd-123-456-789.p2pify.com/3c6e0b8a9c15224a8228b9a98ca1531d -d '{"method":"getblockchaininfo","params":[],"id":1}'
Why no switcher here?

2021-08-17 05:23 UTC, akegaviar commented on docs/operations/bitcoin/tools.md
> +curl https://nd-123-456-789.p2pify.com/3c6e0b8a9c15224a8228b9a98ca1531d -d '{"method":"getblockchaininfo","params":[],"id":1}'
Fixed

2021-08-17 05:23 UTC, akegaviar commented on docs/operations/quorum/tools.md
> +* ENDPOINT — your node HTTPS endpoint.
Fixed

2021-08-17 05:24 UTC, akegaviar commented on docs/operations/quorum/tools.md
> +* ENDPOINT — your Quorum node RPC endpoint. The format is `https://user-name:pass-word-pass-word-pass-word@nd-123-456-789.p2pify.com`. See [View node access and credentials](/platform/view-node-acces
Fixed

2021-08-17 06:00 UTC, akegaviar commented on docs/platform/view-node-access-and-credentials.md
> +## Public chain nodes
Added Quorum

2021-08-17 11:54 UTC, neewy submitted a review, later dismissed

2021-08-17 15:06 UTC, merged