Add relnotes 2.8
chainstack/docs pull request #401
Opened 2021-12-27 11:20 UTC by akegaviar

2021-12-27 11:27 UTC, PekopT approved these changes

2021-12-29 01:01 UTC, easeev requested changes
1. Tezos Hangzhounet support and Florencenet deprecation are missing
2. Should we reflect public API changes in the release notes?
3. Fix release date according to what @PekopT says

2021-12-29 01:30 UTC, akegaviar commented
> Should we reflect public API changes in the release notes?
@SivakovKonstantin @GranderStark @PekopT I don't see any changes in the [API repository](https://github.com/chainstack/api). What am I missing?

> Fix release date according to what @PekopT says
@PekopT please provide a date

2021-12-29 11:45 UTC, PekopT commented on docs/release-notes.md
> +*December 28, 2021*
@akegaviar 
29 Dec 2021

2021-12-29 13:56 UTC, merged