Add Goerli + roles
chainstack/docs pull request #439
Opened 2022-04-06 10:10 UTC by akegaviar

Added Goerli.
Added roles.
Cleaned up the Polygon bridge tutorial + added Goerli.

2022-04-13 00:50 UTC, easeev requested changes

2022-04-13 00:50 UTC, easeev commented on docs/platform/invite-a-user-to-the-organization.md
> +* Admin — the role can invite users, create and delete projects, deploy and delete nodes and networks, change user roles.
>change user roles

I don't think it's possible

You should check but AFAIK the only real difference between Admin and Editor is that Admin has access to billing details/settings and Editor hasn't

2022-04-13 00:50 UTC, easeev commented on docs/platform/invite-a-user-to-the-organization.md
> +* Editor — the role can create and delete projects, deploy and delete nodes and networks.
AFAIK can invite/delete users in the org but we should double check

2022-04-13 08:40 UTC, akegaviar commented on docs/platform/invite-a-user-to-the-organization.md
> +* Admin — the role can invite users, create and delete projects, deploy and delete nodes and networks, change user roles.
Checked with Andrey, what's currently in the PR is correct. Admin can change roles, Editor cannot change roles.

2022-04-13 08:41 UTC, akegaviar commented on docs/platform/invite-a-user-to-the-organization.md
> +* Editor — the role can create and delete projects, deploy and delete nodes and networks.
Checked with Andrey, Editor cannot invite/delete users.

2022-04-13 09:13 UTC, easeev commented on docs/platform/invite-a-user-to-the-organization.md
> +* Admin — the role can invite users, create and delete projects, deploy and delete nodes and networks, change user roles.
Ok, what about billing?

2022-04-13 09:14 UTC, easeev commented on docs/platform/invite-a-user-to-the-organization.md
> +* Admin — the role can invite users, create and delete projects, deploy and delete nodes and networks, change user roles.
BTW who can show me how to change role in the UI? I can't figure out how to do it

2022-04-14 00:27 UTC, akegaviar commented on docs/platform/invite-a-user-to-the-organization.md
> +* Admin — the role can invite users, create and delete projects, deploy and delete nodes and networks, change user roles.
Fixed

2022-04-14 00:59 UTC, easeev commented on docs/release-notes.md
> +  * There are now three roles: <a href="https://support.chainstack.com/hc/en-us/articles/900001563563-Organizations-users-and-members" target="_blank">Admin, Editor, Viewer</a>. Only the Admin role h
```suggestion
  * There are now three roles: <a href="https://support.chainstack.com/hc/en-us/articles/900001563563-Organizations-users-and-members" target="_blank">Admin, Editor, Viewer</a>.
```

2022-04-14 01:02 UTC, merged