Add RPC methods
chainstack/docs pull request #458
Opened 2022-06-10 08:46 UTC by akegaviar

In lieu of [PR#456](https://github.com/chainstack/docs/pull/456)

2022-06-17 09:31 UTC, akegaviar commented
@py-goh done

2022-06-17 09:33 UTC, easeev commented on docs/api/node-json-rpc-api.md
> +For a detailed description of all the available JSON-RPC methods, see [Ethereum Wiki](https://eth.wiki/json-rpc/API)
Full stop missing?

2022-06-17 09:34 UTC, easeev commented on docs/api/node-json-rpc-api.md
> +This page is a collection of JSON-RPC API call examples for Ethereum-based nodes with [web3.js](https://web3js.readthedocs.io/), [web3.py](https://web3py.readthedocs.io/), and [cURL](https://curl.se/
>Ethereum-based

Is it consistent with other docs? I.e. Ethereum-based or EVM-based?

2022-06-21 01:19 UTC, easeev requested changes
See comments

2022-06-22 07:55 UTC, akegaviar commented on docs/.vuepress/config.js
> +                    '/api/node-json-rpc-api',
> in the menu doesn't look good. Platform API could be technically also JSON-RPC API so it's confusing

Changed.

> Solana also has JSON-RPC API but we don't have it here. Will we have it BTW.

Yes, it's planned for the next iteration.

2022-06-22 07:55 UTC, akegaviar commented on docs/api/node-json-rpc-api.md
> +This page is a collection of JSON-RPC API call examples for Ethereum-based nodes with [web3.js](https://web3js.readthedocs.io/), [web3.py](https://web3py.readthedocs.io/), and [cURL](https://curl.se/
Changed.

2022-06-22 07:55 UTC, akegaviar commented on docs/api/node-json-rpc-api.md
> +For a detailed description of all the available JSON-RPC methods, see [Ethereum Wiki](https://eth.wiki/json-rpc/API)
Fixed.

2022-06-22 10:11 UTC, easeev commented on docs/api/node-api-reference.md
> +    content: Collection of JSON-RPC methods available with examples in web3.js, web3.py, eth.rb, and cURL.
```suggestion
    content: Collection of JSON-RPC methods for EVM nodes available with examples in web3.js, web3.py, eth.rb, and cURL.
```

or something similar?

2022-06-22 10:20 UTC, merged