CORE-4060: testnet replaced with devnet for harmony
chainstack/docs pull request #459
Opened 2022-06-15 13:46 UTC by GranderStark

Values were replaced as part of migration from testnet to devnet.

2022-06-17 08:14 UTC, akegaviar commented on docs/operations/harmony/tools.md
> +    * Devnet Shard 0: `1666700000`
`1666900000` see https://docs.harmony.one/home/general/wallets/browser-extensions-wallets/metamask-wallet/adding-harmony

2022-06-17 08:14 UTC, akegaviar commented on docs/operations/harmony/tools.md
> +  * Devnet Shard 0: `1666700000`
`1666900000` see https://docs.harmony.one/home/general/wallets/browser-extensions-wallets/metamask-wallet/adding-harmony

2022-06-17 08:15 UTC, akegaviar commented on docs/operations/harmony/tools.md
> +  * Devnet Shard 0: `1666700000`
`1666900000` see https://docs.harmony.one/home/general/wallets/browser-extensions-wallets/metamask-wallet/adding-harmony

2022-06-17 08:15 UTC, akegaviar commented on docs/operations/harmony/tools.md
> +  * Devnet Shard 0: `1666700000`
`1666900000` see https://docs.harmony.one/home/general/wallets/browser-extensions-wallets/metamask-wallet/adding-harmony

2022-06-17 08:16 UTC, akegaviar commented on docs/tutorials/harmony/simple-metaverse-contract-with-foundry.md
> +* PRIVATE_KEY — the private key to the account that deploys the contract. Must be used without the `0x` prefix. Fund the account with devnet ONE using the [devnet faucet](https://faucet.pops.one/).
http://dev.faucet.easynode.one/

2022-06-17 08:17 UTC, akegaviar commented on docs/tutorials/harmony/simple-metaverse-contract-with-foundry.md
> +1. Open the [Harmony devnet explorer](https://explorer.pops.one/).
https://explorer.ps.hmny.io/

2022-06-17 08:17 UTC, akegaviar commented on docs/tutorials/harmony/simple-metaverse-contract-with-foundry.md
> +1. On the contract page in the [Harmony devnet explorer](https://explorer.pops.one/), click **Write Contract**
https://explorer.ps.hmny.io/

2022-06-17 08:18 UTC, akegaviar requested changes
Please see comments

2022-06-17 15:07 UTC, GranderStark commented
And at the same time same variables were set in UI correctly in the first place. T-T 
Thanks, @akegaviar 
please re-review

2022-06-21 08:38 UTC, akegaviar approved these changes

2022-06-30 01:19 UTC, merged