Docs and links updated
chainstack/docs pull request #461
Opened 2022-06-28 08:59 UTC by Dhruv-2003

1. Polygon mumbai explorer link updated , from POS mainnet explorer ---> POS Mumbai Exlporer
2. ABI encoding format , [abi] 
3. Added points for ABI encoding
4. token mapper link updated to add new token link

2022-06-29 07:20 UTC, akegaviar commented on docs/tutorials/polygon/bridging-erc20-from-ethereum-to-polygon.md
> +1. In the service, provide the [ChildERC20.json](https://github.com/maticnetwork/pos-portal/blob/master/artifacts/ChildERC20.json) ABI data as ([abi])
Can you please change to
```
ABI data as `([abi])`.
```
?

2022-06-29 07:21 UTC, akegaviar requested changes
Thanks a lot @Dhruv-2003 . Can you please implement a minor comment/

2022-06-29 07:29 UTC, Dhruv-2003 commented on docs/tutorials/polygon/bridging-erc20-from-ethereum-to-polygon.md
> +1. In the service, provide the [ChildERC20.json](https://github.com/maticnetwork/pos-portal/blob/master/artifacts/ChildERC20.json) ABI data as ([abi])
The proper data format for encoding, the childERC20.json is abi withing square brackets [abi], other wise it will throw an error .Also we have to add arguements , Either we can provide the encoded data directly instead of letting the user to do it , it is a bit confusing .

2022-06-29 07:31 UTC, akegaviar commented on docs/tutorials/polygon/bridging-erc20-from-ethereum-to-polygon.md
> +1. In the service, provide the [ChildERC20.json](https://github.com/maticnetwork/pos-portal/blob/master/artifacts/ChildERC20.json) ABI data as ([abi])
I'm only asking you to add a full stop and to make sure it's rendering properly in markdown as `([abi])`.

2022-06-29 07:32 UTC, Dhruv-2003 commented on docs/tutorials/polygon/bridging-erc20-from-ethereum-to-polygon.md
> +1. In the service, provide the [ChildERC20.json](https://github.com/maticnetwork/pos-portal/blob/master/artifacts/ChildERC20.json) ABI data as ([abi])
ok sure , I will change it .

2022-06-29 11:47 UTC, Dhruv-2003 commented on docs/tutorials/polygon/bridging-erc20-from-ethereum-to-polygon.md
> +1. In the service, provide the [ChildERC20.json](https://github.com/maticnetwork/pos-portal/blob/master/artifacts/ChildERC20.json) ABI data as ([abi])
I have made the changes .

2022-06-29 11:56 UTC, akegaviar commented on docs/tutorials/polygon/bridging-erc20-from-ethereum-to-polygon.md
> +1. Put your constructor data by adding arguements with the data type:
typo in `arguements`. should be `arguments`

2022-06-29 11:57 UTC, akegaviar requested changes
Thanks @Dhruv-2003 one small typo and we should be good.

2022-06-29 12:03 UTC, akegaviar approved these changes
LGTM

2022-06-30 04:42 UTC, easeev approved these changes
Thanks for your contribution @Dhruv-2003 💙

2022-06-30 04:43 UTC, merged

2022-06-30 05:44 UTC, Dhruv-2003 commented
> Thanks for your contribution @Dhruv-2003 💙

Welcome , It was great working on this tutorial .