Release 3.2.0 (prod)
chainstack/docs pull request #491
Opened 2022-08-23 12:33 UTC by cthtuf

2022-08-23 13:09 UTC, cthtuf commented on docs/release-notes.md
> +* **Protocols**. [Gnosis](/operations/gnosis/networks) support.
Something should be added here

2022-08-24 08:00 UTC, akegaviar requested changes
Please include https://github.com/chainstack/docs/pull/493

2022-08-24 08:36 UTC, cthtuf commented
> Please include #493

fixed

2022-08-24 09:07 UTC, akegaviar approved these changes

2022-08-24 09:37 UTC, PekopT approved these changes
LGTM

2022-08-24 09:37 UTC, merged