Update Node API reference page.
chainstack/docs pull request #494
Opened 2022-08-24 11:33 UTC by soos3d

Fix eth_estimateGas to include the proper block input.

Fix web3.py import statements.

2022-08-24 11:41 UTC, akegaviar approved these changes

2022-08-30 03:35 UTC, akegaviar requested changes

2022-08-30 03:35 UTC, akegaviar commented on docs/tutorials/avalanche/aave-flash-loans-with-brownie.md
> +* Brownie Avalanche network ID — the same Brownie network ID you assigned when pointing Brownie to your Avalanche node. See also [Avalanche tools: Brownie](https://docs.chainstack.com/operations/aval
internal docs path should be relative, not direct links.

2022-08-30 20:18 UTC, soos3d commented on docs/tutorials/avalanche/aave-flash-loans-with-brownie.md
> +* Brownie Avalanche network ID — the same Brownie network ID you assigned when pointing Brownie to your Avalanche node. See also [Avalanche tools: Brownie](https://docs.chainstack.com/operations/aval
Sorry about that, fixed!

2022-08-31 18:06 UTC, closed without merging