Docs update - Add protocol specific API reference pages.
chainstack/docs pull request #517
Opened 2022-09-07 16:22 UTC by soos3d

Added:
* `ethereum-api-reference.md`.
* `arbitrum-api-reference.md`.
* `polygon-api-reference.md`.
* `avalanche-api-reference.md`.

Fixed:
* `node-api-reference.md`.
  * Fixed inconsistencies and quotes. 

Added new pages to `config.js`

2022-09-07 23:58 UTC, akegaviar commented on docs/api/arbitrum-api-reference.md
> +Chainstack supports the Arbitrum testnet on Goerli. You can deploy an Arbitrum Goerli testnet node, then bridge some Goerli ETH using the [testnet Arbitrum brigde](https://bridge.arbitrum.io/?l2Chain
Link to our Arbitrum tools docs section.

2022-09-07 23:58 UTC, akegaviar commented on docs/api/arbitrum-api-reference.md
> +[Arbitrum](https://developer.offchainlabs.com/) is an EVM-compatible sidechain, and one of Ethereum's [scaling solutions](https://chainstack.com/solving-the-blockchain-trilemma-scaling-solutions-for-
Not a sidechain, it's a rollup.

2022-09-08 00:00 UTC, akegaviar commented on docs/api/arbitrum-api-reference.md
> +Chainstack supports the Arbitrum testnet on Goerli. You can deploy an Arbitrum Goerli testnet node, then bridge some Goerli ETH using the [testnet Arbitrum brigde](https://bridge.arbitrum.io/?l2Chain
`Arbitrum Goerli testnet`

2022-09-08 00:01 UTC, akegaviar commented on docs/api/arbitrum-api-reference.md
> +To read data from and send transactions to the Arbitrum blockchain, an application must connect to an Arbitrum node.
@py-goh do you want `Arbitrum node` to be an `Arbitrum RPC node`?

2022-09-08 00:22 UTC, akegaviar commented
We also need to remove `Node API reference` I think now that we targeting to have a separate page for each protocol.

2022-09-08 00:24 UTC, akegaviar commented
Protocol order:

* Ethereum API
* Polygon API
* Avalanche API
* Arbitrum API

2022-09-08 00:27 UTC, akegaviar commented
The see also sections are not rendering

![SCR-20220908-bq9](https://user-images.githubusercontent.com/10195782/189007491-aebdf670-5e14-4e2b-86bf-f09c3821ec81.png)

2022-09-08 00:29 UTC, akegaviar commented on docs/api/avalanche-api-reference.md
> +[Avalanche](https://www.avax.network/) is an EVM-compatible protocol focused on speed and scalability. Avalanche is the fastest smart contracts platform in the blockchain industry, measured by time-t
Remove this:

```
Avalanche is the fastest smart contracts platform in the blockchain industry, measured by time-to-finality.
```
to keep it neutral

2022-09-08 00:29 UTC, akegaviar commented on docs/api/avalanche-api-reference.md
> +The Avalanche network can achieve high throughput, estimated to reach over 4500 transactions per second. Transactions are finalized in under a second while being able to scale to unprecedented levels
Remove this section too.

2022-09-08 00:31 UTC, akegaviar commented on docs/api/polygon-api-reference.md
> +[Polygon POS](https://docs.polygon.technology/docs/develop/getting-started) is an EVM-compatible sidechain, and one of Ethereum's [scaling solutions](https://chainstack.com/solving-the-blockchain-tri
We are renaming `Polygon PoS` to `Polygon` everywhere for simplicity, so drop `POS`

2022-09-08 00:32 UTC, akegaviar commented on docs/api/polygon-api-reference.md
> +This allows Ethereum developers to leverage lower transactions cost and faster transaction speed to scale applications while maintaining the security offered by the Ethereum network.
```
while maintaining the security offered by the Ethereum network.
```
I don't think so. It's a separate chain. So just remove the paragraph.

2022-09-08 00:33 UTC, akegaviar requested changes
Changes please

2022-09-08 02:15 UTC, py-goh commented on docs/api/arbitrum-api-reference.md
> +To read data from and send transactions to the Arbitrum blockchain, an application must connect to an Arbitrum node.
Arbitrum RPC node would be great

2022-09-08 02:16 UTC, akegaviar commented on docs/api/arbitrum-api-reference.md
> +To read data from and send transactions to the Arbitrum blockchain, an application must connect to an Arbitrum node.
@soos3d for all four then please

2022-09-08 02:30 UTC, py-goh commented on docs/api/arbitrum-api-reference.md
> +To read data from and send transactions to the Arbitrum blockchain, an application must connect to an Arbitrum node.
All [protocol] nodes are preferred to be [protocol] RPC nodes

2022-09-08 12:55 UTC, soos3d commented on docs/api/arbitrum-api-reference.md
> +Chainstack supports the Arbitrum testnet on Goerli. You can deploy an Arbitrum Goerli testnet node, then bridge some Goerli ETH using the [testnet Arbitrum brigde](https://bridge.arbitrum.io/?l2Chain
How did I not think about that

2022-09-12 05:23 UTC, akegaviar commented on docs/api/arbitrum/arbitrum-api-reference.md
> +::: tip See also
No full stop, a bullet point, and blank lines please:

```
::: tip See also

* <a href="https://chainstack.com/build-better-with-arbitrum/" target="_blank">Build better with Arbitrum</a>

:::
```

2022-09-12 05:23 UTC, akegaviar commented on docs/api/avalanche/avalanche-api-reference.md
> +::: tip See also
same

2022-09-12 05:26 UTC, akegaviar commented on docs/api/polygon/polygon-api-reference.md
> +::: tip See also
same

2022-09-12 05:26 UTC, akegaviar requested changes
Minor changes

2022-09-12 05:26 UTC, akegaviar commented
@py-goh have a look please

2022-09-12 05:27 UTC, akegaviar commented
Also @soos3d resolve conflicts please

2022-09-12 06:05 UTC, py-goh commented
- Separated URL path LGTM
- Backlinks to BBW Protocol LGTM
- Protocol API Reference still using hash but it's fine since the doc is short. If the Protocol API Reference happens to expand into a super long doc, separated path is preferred

2022-09-13 05:28 UTC, akegaviar requested changes
One more change please. Hopefully final.

Since we'll be at The Merge when this PR is merged, add to all Ethereum API methods that take `latest`, `earliest`, `pending` as parameters the two post merge ones: `safe` and `finalized`. Now they accept all 5: latest, earliest, pending, safe, finalized.

2022-09-13 07:42 UTC, akegaviar commented
> One more change please. Hopefully final.

> Since we'll be at The Merge when this PR is merged, add to all Ethereum API methods that take latest, earliest, pending as parameters the two post merge ones: safe and finalized. Now they accept all 5: latest, earliest, pending, safe, finalized.

Actually, let's make it as a separate PR.

2022-09-13 07:44 UTC, akegaviar approved these changes
LGTM

2022-09-13 09:02 UTC, easeev requested changes
Rebase / fix tests

2022-09-14 02:24 UTC, akegaviar approved these changes
lgtm

2022-09-14 06:40 UTC, merged