Add Solana API
chainstack/docs pull request #534
Opened 2022-09-23 10:18 UTC by soos3d

Added Solana API

- Solana API reference.
- Solana API methods.

2022-09-30 05:58 UTC, akegaviar commented on docs/api/solana/getbalance.md
> +Solana API method that returns the balance of the account of the provided Public key. The value is returned in Gwei.
Gwei is an Ethereum term and it can't exist in Solana

2022-09-30 05:59 UTC, akegaviar commented on docs/api/solana/getbalance.md
> +* `address` - Pubkey of the account to query, as base-58 encoded string.
Change Pubkey to "public key" everywhere

2022-09-30 08:08 UTC, akegaviar commented on docs/api/solana/getaccountinfo.md
> +* `address` - Pubkey of the account to query, as base-58 encoded string.
Lists are: `* word — word`.

Notice the em dash

2022-09-30 08:10 UTC, akegaviar requested changes
@conor2e @ginstagram review the PR

2022-09-30 08:10 UTC, akegaviar commented on docs/api/solana/getblock.md
> +  * `(optional) transactionDetails: <string>` - level of transaction detail to return, either "full", "accounts", "signatures", or "none". The default detail level is "full" if the parameter is not p
we shouldn't be using quotes to mark values.

2022-09-30 09:50 UTC, ginstagram commented on docs/api/solana/accountsubscribe.md
> +Solana API method to subscribe to an account to receive notifications when the lamports or data for a given account public key changes.
Solana API method _that subscribes to_...

2022-09-30 09:52 UTC, ginstagram commented on docs/api/solana/accountsubscribe.md
> +  * `encoding: <string>` - encoding for Account data, either "base58" (slow), "base64", "base64+zstd" or "jsonParsed". "jsonParsed" encoding attempts to use program-specific state parsers to return m
Please make sure you're using the sentence case for all annotations in the lists

2022-09-30 11:52 UTC, conor2e commented on docs/api/solana/accountunsubscribe.md
> +* `<number>` - id of the account Subscription to cancel.
Inconsistent capitalization - _subscription_ should be sentence case.

2022-09-30 11:58 UTC, conor2e commented on docs/api/solana/getblock.md
> +  * `(optional) encoding: <string>` - encoding for each returned Transaction, either "json", "jsonParsed", "base58" (slow), "base64". If the parameter is not provided, the default encoding is "json".
Inconsistent capitalization - _transaction_ should be sentence case.

2022-09-30 12:08 UTC, conor2e commented on docs/api/solana/gethealth.md
> +* `response` - If the node is healthy: "ok" If the node is unhealthy, a JSON RPC error response is returned. The specifics of the error response are UNSTABLE and may change in the future
Inconsitent punctuation - use comma instead of colon after _healthy_.

2022-09-30 12:41 UTC, ginstagram commented on docs/api/solana/getblockproduction.md
> +    * `byIdentity: <object>` - a dictionary of validator identities, as base-58 encoded strings. Value is a two element array containing the number of leader slots and the number of blocks produced.
Please I suggest choosing one option when describing parameters: 

- to use articles in all annotations
- omit them in all annotations

2022-09-30 13:47 UTC, ginstagram commented on docs/api/solana/getlatestblockhash.md
> +Solana API method that returns the identity and transaction information about a confirmed block in the ledger.
Has the same description as `getblock` endpoint. Please change it according to the endpoint name

2022-09-30 13:54 UTC, ginstagram commented on docs/api/solana/gethealth.md
> +If one or more `--known-validator` arguments are provided to `solana-validator`, "ok" is returned when the node has within `HEALTH_CHECK_SLOT_DISTANCE` slots of the highest known validator, otherwise
Checking what this paragraph is about. When we are sure, it would probably be rewritten.

2022-09-30 14:07 UTC, ginstagram commented on docs/api/solana/getlatestblockhash.md
> +::: tip
@akegaviar We want to rephrase this tip a bit so that we won't have to update the Chainstack version manually. Can we claim that Chainstack always uses the latest version of Solana?

2022-09-30 14:44 UTC, ginstagram commented on docs/api/solana/gettransaction.md
> +  * `<object>` - if the transaction is confirmed, an object with the following fields:
This list item must be on level 1, I guess. And all its children must be moved to an upper level

2022-09-30 15:08 UTC, ginstagram commented on docs/api/solana/solana-api-reference.md
> +To read data from and send transactions to the Solana blockchain, an application must connect to an Solana RPC node.
Here and on string 27 change an Solana... to a Solana

2022-09-30 15:18 UTC, ginstagram requested changes
Make sure to make the abovementioned edits :)

2022-09-30 16:51 UTC, soos3d commented on docs/api/solana/getbalance.md
> +Solana API method that returns the balance of the account of the provided Public key. The value is returned in Gwei.
True, the value returned matches Gwei so I got confused about that. Would it be ok to put it like this?

```md
**Returns:** 

* `quantity` - The integer value of the current balance with 9 decimals.

::: tip

Divide the value returned by 1000000000 to convert to a whole Solana measure unit.

:::
```

2022-09-30 19:56 UTC, soos3d commented on docs/api/solana/gethealth.md
> +If one or more `--known-validator` arguments are provided to `solana-validator`, "ok" is returned when the node has within `HEALTH_CHECK_SLOT_DISTANCE` slots of the highest known validator, otherwise
BTW this method is not supported by the JS and Python libraries. I included it because I thought it was interesting but we can probably remove it since is not supported by the libraries and only available with cURL. What do you think @akegaviar ?

2022-09-30 20:10 UTC, soos3d commented on docs/api/solana/getlatestblockhash.md
> +Solana API method that returns the identity and transaction information about a confirmed block in the ledger.
good catch 😅

2022-10-01 00:11 UTC, akegaviar commented on docs/api/solana/getbalance.md
> +Solana API method that returns the balance of the account of the provided Public key. The value is returned in Gwei.
No, read the docs please.

https://docs.solana.com/introduction#what-are-sols

2022-10-01 00:14 UTC, akegaviar commented on docs/api/solana/gethealth.md
> +If one or more `--known-validator` arguments are provided to `solana-validator`, "ok" is returned when the node has within `HEALTH_CHECK_SLOT_DISTANCE` slots of the highest known validator, otherwise
> I included it because I thought it was interesting

Yes, we must keep it

2022-10-01 00:14 UTC, soos3d commented on docs/api/solana/getbalance.md
> +Solana API method that returns the balance of the account of the provided Public key. The value is returned in Gwei.
I looked for something like that everywhere except than in the right place. I'll fix it

2022-10-01 00:20 UTC, akegaviar commented on docs/api/solana/getlatestblockhash.md
> +::: tip
> We want to rephrase this tip a bit so that we won't have to update the Chainstack version manually.

Correct

> Can we claim that Chainstack always uses the latest version of Solana?

No, our goal is security and stability, which often means not updating to the latest version directly.

In this case, we can just remove any version mention. We are on 1.9, so no need for any 1.8 methods anyway.

2022-10-04 07:50 UTC, conor2e commented
lgtm

2022-10-04 07:56 UTC, ginstagram commented on docs/api/solana/getepochinfo.md
> +  * `(optional) commitment: <string>` — the ommitment.
lost the C in commitment

2022-10-04 08:02 UTC, ginstagram commented on docs/api/solana/logssubscribe.md
> +* `<integer>` — Subscription id (needed to unsubscribe).
article + lower case

2022-10-04 08:03 UTC, ginstagram commented on docs/api/solana/slotsubscribe.md
> +* `<integer>` — the subscription id needed to unsubscribe.
In docs/api/solana/logssubscribe.md the same goes in parenthesis. Please use it here too

2022-10-04 08:05 UTC, ginstagram reviewed
Needs small tweaks to be polished

2022-10-04 08:33 UTC, conor2e approved these changes
Some very minor typos but I approve.

2022-10-04 08:33 UTC, conor2e commented on docs/api/solana/getbalance.md
> +Solana API method that returns the balance of the account of the provided Public key.
Use sentence case for _public key_ consistently outside of the code.

2022-10-04 08:43 UTC, ginstagram approved these changes

2022-10-04 15:20 UTC, soos3d commented
Fixed the last typos and inconsistencies.

2022-10-05 10:53 UTC, akegaviar commented on docs/api/solana/solana-api-reference.md
> +Find useful [Solana tools](/operations/solana/tools#tools) in the Chainstack docs.
should be `/operations/solana/tools`

2022-10-05 10:55 UTC, akegaviar commented on docs/api/solana/websocket-subscriptions.md
> +# Solana API websocket subscriptions
WebSocket (protocol name like HTTP)

2022-10-05 10:59 UTC, akegaviar commented on docs/api/solana/accountsubscribe.md
> +* `<number>` — the subscription id which is needed to unsubscribe.
`id` — I always struggle with how we should spell/capitalize it as short for identification/identity. Let's pick a version, put it in our style guide and set it in stone and commit to it.

@conor2e @ginstagram

2022-10-05 10:59 UTC, akegaviar requested changes
A few more changes

2022-10-05 11:19 UTC, conor2e commented on docs/api/solana/accountsubscribe.md
> +* `<number>` — the subscription id which is needed to unsubscribe.
Lera actually brought this up with me last week. I recommend using ID. The guide that I like to refer to and usually am in agreement with is the _Google developer documentation style guide_, which I think we should use as our basis for our guide. For example: https://developers.google.com/style/word-list#letter-i

2022-10-05 11:31 UTC, ginstagram commented on docs/api/solana/accountsubscribe.md
> +* `<number>` — the subscription id which is needed to unsubscribe.
I have nothing to add. We agreed on that :)

2022-10-05 11:36 UTC, soos3d commented on docs/api/solana/accountsubscribe.md
> +* `<number>` — the subscription id which is needed to unsubscribe.
ok I'll change all of them to ID then!

2022-10-07 00:56 UTC, akegaviar approved these changes

2022-10-07 00:57 UTC, akegaviar commented
@conor2e @ginstagram stamp your approve please if all is okay

2022-10-07 06:59 UTC, conor2e approved these changes
All looks good to me.

2022-10-07 07:21 UTC, ginstagram approved these changes
Good work!

2022-10-09 23:55 UTC, akegaviar commented
@PekopT please merge and put on prod + update master

2022-10-10 13:54 UTC, merged