Sepolia
chainstack/docs pull request #538
Opened 2022-09-27 13:22 UTC by conor2e

Updated the docs to include references to the newly supported Ethereum Sepolia testnet network. Added the network and ChainID to the _Operations>Ethereum>Tools_ section.

2022-09-27 23:45 UTC, akegaviar commented on docs/operations/ethereum/tools.md
>      * Ropsten: `3`
Change the order please to:

* Goerli
* Sepolia
* Ropsten
* Rinkeby

2022-09-27 23:48 UTC, akegaviar commented on docs/operations/ethereum/tools.md
> +2. Click **Save**.
What does it render to when building locally? We are using `1.` for [numbered lists](https://carpentries-incubator.github.io/markdown-intro/06-lists/index.html) whenever possible.

This way it's easy to slide a new step into the list without thinking much about the resulting numbers.

2022-09-27 23:48 UTC, akegaviar commented on docs/operations/ethereum/tools.md
>    * Ropsten: `3`
Order please

* Goerli
* Sepolia
* Ropsten
* Rinkeby

2022-09-27 23:49 UTC, akegaviar requested changes
Ordered list and the testnet order please

2022-09-28 07:19 UTC, conor2e commented on docs/operations/ethereum/tools.md
> +2. Click **Save**.
That's strange, I didn't modify the number so it must have changed automatically when I added the content above it. Thanks for highlighting it. It resolved fine with 2, but I have changed it back to 1.

2022-09-28 07:38 UTC, conor2e commented on docs/operations/ethereum/tools.md
>    * Ropsten: `3`
The list was in order of ChainID value, lowest to highest, so I just added Sepolia at the end. Including Mainnet, I have changed the order to the following as requested:

- Mainnet 1
- Goerli 5
- Sepolia 11155111
- Ropsten 3
- Rinkeby 4

2022-09-28 08:33 UTC, akegaviar commented on docs/platform/join-a-public-network.md
> +1. Under **Blockchain network**, select **Mainnet**, **Ropsten testnet**, **Rinkeby testnet**, **Goerli testnet**, or **Sepolia testnet**. Click **Next**.
same for order here too please: goeri, sepolia, ropsten, rinkeby

2022-09-28 08:34 UTC, akegaviar requested changes
Protocol order

2022-09-28 08:34 UTC, akegaviar commented on docs/platform/supported-protocols.md
>  	* Ropsten testnet
same here for order

2022-09-28 09:21 UTC, conor2e commented on docs/platform/supported-protocols.md
>  	* Ropsten testnet
Updated both files.

2022-09-29 07:06 UTC, akegaviar approved these changes

2022-10-03 12:46 UTC, merged