Add Cronos docs
chainstack/docs pull request #542
Opened 2022-10-10 13:37 UTC by ginstagram

* Add quickstart, platform, operations, tutorials, blockchains sections for Cronos
* Add relnotes for 3-5-1, 3-5-5, 3-5-6 and Solana API docs
* Fix several typos

2022-10-11 12:51 UTC, akegaviar commented on docs/release-notes.md
> +* **Documentation**. Solana API [reference](/api/solana).
the correct link is `/api/solana/solana-api-reference`

2022-10-11 13:03 UTC, akegaviar commented on docs/tutorials/cronos/nft-dutch-auction-contract-with-hardhat.md
> +1. With Metamask, fund your wallet with test CRO tokens from the [Cronos official faucet](https://cronos.org/faucet).
MetaMask

2022-10-11 13:03 UTC, akegaviar commented on docs/tutorials/cronos/nft-dutch-auction-contract-with-hardhat.md
> +* <a href="https://console.chainstack.com/" target="_blank">Chainstack account</a> to deploy a Cronos Testnet node.
`testnet`

2022-10-11 13:05 UTC, akegaviar commented on docs/tutorials/cronos/nft-dutch-auction-contract-with-hardhat.md
> +In your project directory, run `npx hardhat`. Select Create a JavaScript project and agree to install the sample project's dependencies. This will create a sample project directory with a smart contr
`Select Create a JavaScript `?

If it's a UI element, it needs proper style. For example, in bold.

2022-10-11 13:08 UTC, akegaviar commented on docs/tutorials/cronos/nft-dutch-auction-contract-with-hardhat.md
> +To deploy your smart contract on the Cronos testnet, you will need some Test CRO tokens. See the [Cronos faucet](https://cronos.org/faucet).
Is it `Test CRO` or `test CRO`? There are different versions here in the tutoril.

2022-10-12 13:19 UTC, akegaviar commented on docs/release-notes.md
> +* **Documentation**. Solana API [reference](/api/solana-api-reference).
`/api/solana/solana-api-reference`

2022-10-12 13:23 UTC, akegaviar commented
Change the protocol order everywhere in the commit please to:

* Cronos
* Fantom

2022-10-12 13:24 UTC, akegaviar requested changes
Some minor changes

2022-10-13 12:23 UTC, akegaviar approved these changes

2022-10-14 07:13 UTC, NikitosnikN approved these changes

2022-10-14 07:14 UTC, merged