Add Aptos docs
chainstack/docs pull request #561
Opened 2022-10-28 11:21 UTC by ginstagram

## Description

Add Aptos docs to Quickstart, Platform, Operations, Tutorials, and Blockchains.
Update config.js respectively

2022-10-28 12:17 UTC, akegaviar commented on docs/operations/aptos/tools.md
> +https://nd-981-674-322.int.chainstack.com/v1/blocks/by_height/{block_height}
Change to the dummy

2022-10-28 12:18 UTC, akegaviar commented on docs/operations/aptos/tools.md
> +  --url https://nd-981-674-322.int.chainstack.com/v1/blocks/by_height/2047048\
Change to dummy

2022-10-28 12:36 UTC, soos3d commented on docs/operations/aptos/tools.md
> +https://nd-981-674-322.int.chainstack.com/v1/blocks/by_height/{block_height}
This is already a fake endpoint, but let's update it if we have a dummy that we use to keep consistency.

2022-10-28 13:27 UTC, ginstagram commented on docs/operations/aptos/tools.md
> +https://nd-981-674-322.int.chainstack.com/v1/blocks/by_height/{block_height}
done

2022-10-28 13:27 UTC, ginstagram commented on docs/operations/aptos/tools.md
> +  --url https://nd-981-674-322.int.chainstack.com/v1/blocks/by_height/2047048\
done

2022-10-31 05:36 UTC, akegaviar commented on docs/blockchains/aptos.md
> +Aptos is a permissionless non-EVM compatible layer 1 novel chain created using [Move](https://move-language.github.io/move/), which is a Rust-based computer programming language.
Let's drop `novel`, I don't think it fits here.

2022-10-31 05:37 UTC, akegaviar commented on docs/blockchains/aptos.md
> +Aptos is a permissionless non-EVM compatible layer 1 novel chain created using [Move](https://move-language.github.io/move/), which is a Rust-based computer programming language.
> created using [Move](https://move-language.github.io/move/)

I don't think it's created using Move. It utilizes/uses Move/

2022-10-31 05:38 UTC, akegaviar commented on docs/blockchains/aptos.md
> +    content: Aptos is a layer 1 novel chain created using Move, which is a Rust-based computer programming language.
Drop `computer`.

2022-10-31 05:57 UTC, akegaviar commented on docs/tutorials/aptos/publish-module-to-save-and-retrieve-message-on-aptos.md
> +Aptos uses its own terminology for widely-known web3 entities. Smart contracts are called *Modules* and are written in the [Move language](https://move-language.github.io/move/). Modules are also not
Across all our assets, we use `web3` and `Web` interchangeably. Let's settle on [Web3 capitalized](https://en.wikipedia.org/wiki/Web3), add it to our style guide and make sure we use `Web3` across all assets.

2022-10-31 05:59 UTC, akegaviar commented on docs/tutorials/aptos/publish-module-to-save-and-retrieve-message-on-aptos.md
> +1. Save and retrieve a message on the Aptos chain
Full stop?

2022-10-31 06:00 UTC, akegaviar commented on docs/tutorials/aptos/publish-module-to-save-and-retrieve-message-on-aptos.md
> +1. Add your [Chainstack endpoint](/platform/view-node-access-and-credentials). Paste your Aptos node endpoint deployed with Chainstack, for example: `https://nd-123-456-789.int.chainstack.com/`.
> int.chainstack.com

This is dev, don't use it in public docs. For public docs, it's `p2pify`, same as prod

2022-10-31 06:02 UTC, akegaviar requested changes
Changes please

2022-10-31 07:34 UTC, akegaviar submitted a review, later dismissed

2022-10-31 08:06 UTC, conor2e commented on docs/blockchains/aptos.md
> +Aptos is a permissionless non-EVM compatible layer 1 novel chain created using [Move](https://move-language.github.io/move/), which is a Rust-based computer programming language.
I used the word novel as it was referred to in [this article](https://coinmarketcap.com/alexandria/article/what-is-aptos-the-ultimate-guide-to-the-aptos-ecosystem), but I'll remove it now.

2022-10-31 08:11 UTC, conor2e commented on docs/blockchains/aptos.md
> +Aptos is a permissionless non-EVM compatible layer 1 novel chain created using [Move](https://move-language.github.io/move/), which is a Rust-based computer programming language.
i referred to [this article](https://news.bitcoin.com/vc-backed-blockchain-project-aptos-reveals-protocols-mainnet-has-arrived/) for Move and went with "used" as opposed to more colourful terms like "crafted by", but will change to "uses" as requested.

2022-10-31 08:17 UTC, conor2e commented on docs/blockchains/aptos.md
> +Aptos is a permissionless non-EVM compatible layer 1 novel chain created using [Move](https://move-language.github.io/move/), which is a Rust-based computer programming language.
I have changed the sentence to the following: "Aptos is a permissionless non-EVM compatible layer 1 chain created by utilizing Move, which is a Rust-based computer programming language."

2022-10-31 08:24 UTC, conor2e commented on docs/blockchains/aptos.md
> +Aptos is a permissionless non-EVM compatible layer 1 novel chain created using [Move](https://move-language.github.io/move/), which is a Rust-based computer programming language.
Nevermind, Lera made all the requested changes already.

2022-12-23 10:00 UTC, akegaviar submitted a review, later dismissed

2023-01-10 05:23 UTC, akegaviar approved these changes

2023-01-10 07:00 UTC, cthtuf approved these changes

2023-01-10 07:00 UTC, Maxitosh approved these changes

2023-01-10 07:03 UTC, merged