Add testnet2 for StarkNet and minor issues
chainstack/docs pull request #567
Opened 2022-11-15 09:12 UTC by ginstagram

## Description
Add testnet2 for StarkNet
Add rel notes
Fix contact form link
Fix Ethereum API docs link

## Related Issue
https://github.com/chainstack/docs/issues/566

2022-11-15 09:23 UTC, akegaviar commented on docs/api/ethereum/eth_getlogs.md
> +  * `topics` - (optional) Array of `DATA` topics. Topics are order-dependent. [See Ethereum official documentation](https://ethereum.org/en/developers/docs/apis/json-rpc/#ops-deployments-custom) to l
Let's keep "See" and the linked part separate as we currently do.

eg `See [Ethereum official documentation]`.

2022-11-15 09:38 UTC, akegaviar commented on docs/operations/starknet/networks.md
> +For development purposes on the testnet and testnet2, fund your accounts with [L2 Goerli ETH](https://faucet.goerli.starknet.io/).
@ginstagram @soos3d Will this fund the account on testnet2?

Also, the faucet doesn't seem to be working.

Check what the deal with the testnet1 and tesnet2 faucets is and then either remove the mention here or add information that works for either/both testnets.

We need high precision working instructions.

2022-11-15 09:49 UTC, akegaviar commented on docs/operations/starknet/networks.md
> +* Testnet2 — alternative public StarkNet testnet. L2 to the Ethereum Goerli testnet.
Needs better description.

It's not clear why it's an alternative. https://community.starknet.io/t/calling-for-proposals-for-naming-starknets-testnets/2287

It's a less congested test network for dapp developers. something like that.

2022-11-15 09:54 UTC, akegaviar requested changes
Changes please. Needs some research.

2022-11-16 06:39 UTC, akegaviar commented on docs/platform/supported-cloud-hosting-providers.md
> +Want to request a cloud provider or region support? <a href="https://ideas.chainstack.com/feature-requests" target="_blank">Contact us</a>.
This and other case like this—it's no longer "Contact us" though. It's more of a check and vote on the existing feature requests or submit a new one. < Something like that.

2022-11-16 06:40 UTC, akegaviar commented on docs/release-notes.md
> +* **Protocols**. [StarkNet](/operations/starknet/networks) testnet2 support for elastic and dedicated nodes.
change to `testnet2 (Goerli2)`.

2022-11-16 06:40 UTC, akegaviar requested changes
Changes please

2022-11-16 06:59 UTC, akegaviar approved these changes

2022-11-16 08:04 UTC, conor2e commented
@akegaviar @ginstagram I'm approving this PR but going forward, we should clarify with the support team which links we should be promoting to users and consistently clarify our instructions:

- They can view a list of existing feature requests on the ideas website and can "create a post": https://ideas.chainstack.com/feature-requests. 
- They can "submit a request" on the support website here: https://support.chainstack.com/hc/en-us/requests/new
- They can also contact support on the main website, or "_Reach out to us for custom solutions, feature requests, feedback, and any questions you may have regarding Chainstack’s pricing and infrastructure._" here: https://chainstack.com/contact/
- We also ask them to contact us and send them to the support website home page, where it's not really clear from there how to contact us: https://support.chainstack.com/hc/en-us

We should also clarfiy:

- Do they need to create a support account to be able to submit a request on the support website?
- Do they need to create an "ideas.chainstack.com" account to create a post (are these separate accounts)?

2022-11-16 08:04 UTC, conor2e approved these changes

2022-11-16 08:15 UTC, merged

2022-11-16 10:49 UTC, conor2e commented on docs/release-notes.md
> +*November 14*
@ginstagram You left the year out of the date here. Please fix in the next release.