Marketplace guidelines
chainstack/docs pull request #568
Opened 2022-11-22 15:35 UTC by conor2e

## Description
Guidelines for app developers on listing requirements for the Chainstack Marketplace, and instructions on how to submit a request to get their app added.

2022-11-22 15:43 UTC, conor2e commented
@akegaviar I've added a the new file in a temporary location so I welcome feedback on the title, where it should be located in the top level, etc.

2022-11-23 08:02 UTC, ginstagram commented on docs/.vuepress/config.js
> +        '/marketplace'
On the call last Friday, we decided to add Subgraphs under the API level but always before relnotes. I would suggest this order:
...
- API
- Subgraphs (in future)
- Chainstack Marketplace

2022-11-23 08:15 UTC, ginstagram commented on docs/marketplace.md
> +* **Applications**: third-party apps to install on your nodes that add advanced capabilities to your networks.
I would suggest replacing colons with em dashes because we always use them in such cases.

2022-11-23 08:19 UTC, ginstagram commented on docs/marketplace.md
> +
Here and further, there are extra line breaks between paragraphs.

2022-11-23 08:21 UTC, ginstagram commented on docs/marketplace.md
> +* **OAuth2 integration**: Your app must use the OAuth2 authorization method. OAuth2 is a protocol that lets external applications request authorization to private details in a user's account without
I would suggest using em dashes instead of colons + lowercase for explanations.

2022-11-23 08:22 UTC, ginstagram commented on docs/marketplace.md
> +* **Webhooks**: For privacy-compliance purposes, your app must be set up to use webhooks. OAuth2 authorization is required to access Webhooks.
At the end of the second sentence, _Webhooks_ -> _webhooks_.

2022-11-23 08:47 UTC, ginstagram commented on docs/marketplace.md
> +* A **one-pager** for the Chainstack support team, summarising the key features of you app.
_summarising_ -> _summarizing_ as we use AmE

2022-11-23 08:52 UTC, ginstagram commented on docs/release-notes.md
> +* **Documentation**. [Chainstack Marketplace listing guidelines](/marketplace/starknet/networks).
wrong link

2022-11-23 10:03 UTC, ginstagram commented on docs/marketplace.md
> +* **Applications**: third-party apps to install on your nodes that add advanced capabilities to your networks.
Absolutely agree on merging them.  
We do have this inconsistency in relnotes, but that's how they are written :) Maybe we should change that too. Here's the style guide for bulleted lists that I've been using the whole time: https://www.notion.so/chainstack/Content-style-guide-4fd1717f8303425b9f709c5d6d47297c#7090d030522242d8b5a8a5b866757735

2022-11-23 10:27 UTC, conor2e commented on docs/.vuepress/config.js
> +        '/marketplace'
Changed to under API. Feel free to check, @akegaviar.

2022-11-23 11:20 UTC, ginstagram approved these changes
LGTM

2022-11-24 09:02 UTC, akegaviar commented on docs/marketplace.md
> +* **OAuth2 integration** — your app must use the OAuth2 authorization method. OAuth2 is a protocol that lets external applications request authorization to private details in a user's account without
Here and everywhere, use the official name `OAuth 2.0`

2022-11-24 09:04 UTC, akegaviar commented on docs/marketplace.md
> +* An **SLA** for our support team (Community, Business processes from the app side, etc.).
Why caps for Community and Business? I suggest normal sentence case.

2022-11-24 09:05 UTC, akegaviar commented on docs/marketplace.md
> +* **Description** — enter an informative, well written, description of your app.
well-written?

Why is there a comma after `well written`?

2022-11-24 09:07 UTC, akegaviar commented on docs/marketplace.md
> +* **Screenshots** — some screenshots of your application that we can include on the Chainstack Marketplace.
`app` is used in all other places, so this needs to be changed to `app` as well instead of application

2022-11-24 09:08 UTC, akegaviar requested changes
Changes

2022-11-24 11:23 UTC, akegaviar approved these changes

2022-11-24 11:24 UTC, ginstagram approved these changes

2022-11-24 11:27 UTC, merged

2022-11-29 09:32 UTC, conor2e commented on docs/marketplace.md
> +* **OAuth2 integration** — your app must use the OAuth2 authorization method. OAuth2 is a protocol that lets external applications request authorization to private details in a user's account without
Added to our style guide.