Feature/solana api new methods
chainstack/docs pull request #570
Opened 2022-11-28 10:19 UTC by ginstagram

## Description
Updates of Solana API reference and misc

add 5 new methods
describe limitations for Solana API
edit previously added methods for Solana API
change heading from Chainstack Marketplace to Marketplace
add release notes
change version

2022-11-28 10:29 UTC, akegaviar commented on docs/api/solana/solana-api-reference.md
>  When communicating with a Solana RPC node, the Solana client implements a JSON-RPC specification, a communication protocol allowing one to make remote calls and execute them as if they were made loca
There's as typo in 

```
To read data from and send transactions to the Solana blockchain, an application must connect to an Solana RPC node.
```

2022-11-28 10:42 UTC, akegaviar commented on docs/api/solana/getmultipleaccounts.md
> +This method is currently disabled for Sonala devnet elastic nodes.
`Sonala`

2022-11-28 10:44 UTC, akegaviar commented on docs/api/solana/getmultipleaccounts.md
> +# getMultipleAccounts
Page not rendering. 
![SCR-20221128-q0n](https://user-images.githubusercontent.com/10195782/204258336-948bc6bc-8dec-4394-845b-bd747e394f4a.png)

2022-11-28 10:50 UTC, ginstagram commented on docs/api/solana/getmultipleaccounts.md
> +# getMultipleAccounts
> It renders on https://docs.dev.chainstack.com/api/solana/getmultipleaccounts

2022-11-28 10:52 UTC, akegaviar commented on docs/api/solana/getprogramaccounts.md
> +This method is currently disabled for Sonala devnet elastic nodes.
`Sonala`

2022-11-28 10:53 UTC, akegaviar commented on docs/api/solana/gettokenaccountsbydelegate.md
> +This method is currently disabled for Sonala devnet elastic nodes.
Fix all Sonalas please

2022-11-28 10:59 UTC, akegaviar requested changes
Changes please

2022-11-28 17:19 UTC, soos3d submitted a review, later dismissed
LGTM

2022-11-29 07:30 UTC, akegaviar commented on docs/api/solana/getblocks.md
>  ::: tip
Make it consistent please with the other blocks here.

ie 

```
::: tip Information
```

2022-11-29 07:51 UTC, akegaviar commented on docs/api/solana/getmultipleaccounts.md
> +This method is currently disabled for Solana devnet elastic nodes.
Here and everywhere

```
elastic Solana nodes on the devnet
```

or

```
elastic Solana devnet nodes
```

Guys, we have one strict order that needs to be consistent across all assets. Add it to our style guide on notion and commit to it please.

[Example](https://docs.chainstack.com/operations/ethereum/debug-and-trace-apis) of where it's implemented correctly: `elastic Ethereum archive node`.

If we add network to it, then it's `elastic Ethereum archive mainnet node` or `elastic Ethereum archive node on the mainnet`.

The order should be strict and it's [type](https://docs.chainstack.com/operations/ethereum/types) [blockchain](https://docs.chainstack.com/blockchains/ethereum) [mode](https://docs.chainstack.com/operations/ethereum/modes) [network](https://docs.chainstack.com/operations/ethereum/networks) node.

2022-11-29 07:53 UTC, akegaviar requested changes
Changes and make sure the order is in the style guide.

2022-11-29 08:14 UTC, ginstagram commented on docs/api/solana/getmultipleaccounts.md
> +This method is currently disabled for Solana devnet elastic nodes.
Added to the content style guide

2022-11-29 08:48 UTC, akegaviar approved these changes

2022-11-29 11:40 UTC, conor2e requested changes
Some minor formatting checks required.

2022-11-29 11:40 UTC, conor2e commented on docs/api/solana/gettokenaccountsbyowner.md
> +  * `mint: <string>` - the public key of the NFT collection, as a base-58 encoded string;
Check punctuation at the end of this line and the next.

2022-11-29 11:40 UTC, conor2e commented on docs/api/solana/accountsubscribe.md
> +  * `encoding: <string>` — the encoding for account data, either `base58` (slow), `base64`, `base64+zstd`, or `jsonParsed`. `base58` is limited to account data of less than 128 bytes. `base64` will r
base64 should have hyphen in last sentence.

2022-11-29 13:53 UTC, akegaviar approved these changes

2022-11-29 13:53 UTC, conor2e approved these changes

2022-11-29 13:53 UTC, merged