subgraph doc fixes
chainstack/docs pull request #574
Opened 2022-12-07 12:51 UTC by conor2e

## Description
Fixed the folllowing on the Subgraphs document:
- URLs for Deployment command and Querys updated to match latest version on prod.
- Details box at top of page changed to Warning.
- Email address changed to _support@chainstack.com_.

2022-12-07 14:26 UTC, akegaviar commented on docs/subgraphs.md
> -::: details
I suggest changing `::: warning` to `::: tip Information`

2022-12-07 14:38 UTC, akegaviar requested changes
Changes please

2022-12-07 15:00 UTC, conor2e commented on docs/subgraphs.md
> -::: details
Hi @akegaviar. I'll assume I should do this for the other Tip lower in the page in the "Deploy a subgraph" section to be consistent. I'll also add it to our style guide as the standard for Tips that aren't "See also".

2022-12-07 15:05 UTC, akegaviar commented on docs/subgraphs.md
> -::: details
Okay

2022-12-08 05:27 UTC, akegaviar approved these changes

2022-12-08 06:02 UTC, ginstagram approved these changes
LGTM

2022-12-08 07:49 UTC, merged