WIP Add Filecoin docs
chainstack/docs pull request #580
Opened 2023-01-13 10:51 UTC by akegaviar

2023-01-13 10:53 UTC, akegaviar commented
to add:

* cross-link the tutorial section
* relnotes

2023-01-13 10:53 UTC, akegaviar commented
@soos3d please add your tutorial to this PR

2023-01-13 11:15 UTC, ginstagram commented on docs/operations/filecoin/tools.md
> +    content: Learn how to interact with your Filecoin node, deploy smart contracts through your node, and develop dapps.
Don't we spell "DApps" properly when in meta?

2023-01-13 11:16 UTC, akegaviar commented on docs/operations/filecoin/tools.md
> +    content: Learn how to interact with your Filecoin node, deploy smart contracts through your node, and develop dapps.
Fixced

2023-01-17 04:11 UTC, akegaviar commented on docs/tutorials/filecoin/deploy-using-hardhat.md
> +---
filename should be `deploy-an-erc20-token-on-filecoin-with-hardhat` <— filenames follow the title.

Also will need to be changed in config.js and crosslinks

2023-01-17 04:11 UTC, akegaviar commented on docs/tutorials/filecoin/deploy-using-hardhat.md
> +# Deploy an ERC20 token on Filecoin with Hardhat
ERC-20

2023-01-17 04:24 UTC, akegaviar reviewed
@soos3d changes please

2023-01-17 04:24 UTC, akegaviar commented on docs/tutorials/filecoin/deploy-using-hardhat.md
> +ERC-20 is the token implementation standard for smart contracts, and it defines a set of rules that a token contract must follow to be considered an ERC-20 token. These rules include how tokens are t
Explaining what is ERC-20, OpenZeppelin, Hardhat in 2023 to the FIlecoin developers is not what we are after. I'm pretty sure 99.9% of this tutorial's target audience know these tools and standards pretty well.

Instead, I suggest you swap this paragraph with an explanation of FVM, FEVM (and mention that it's a first-class citizen) with a link to where to follow the FEVM implementation progress/details on GitHub or something similar.

Also, touch on actors (native to FVM + link) and evm smart contracts.

And then the rest is the same erc20 guide that shows how to do an evm native transaction (contract deployment) on Filecoin.

And then before the `## Conclusion` part, please link to a deployed contract from your example on the explorer and do a brief overview of what the messages and fields there mean (doesn't need to be very detailed, but an overview for general understanding and direction).

2023-01-17 11:31 UTC, ginstagram reviewed
Left several comments, otherwise LGTM. Gonna hit approve once all the content is added and edited

2023-01-17 11:31 UTC, ginstagram commented on docs/tutorials/filecoin/deploy-using-hardhat.md
> +- The contract mints 1000000000 tokens when it is deployed. The owner of the smart contract can mint more tokens by calling the `mint` function.
1000000000 -> 1,000,000,000 as per style guide

2023-01-17 11:31 UTC, ginstagram commented on docs/tutorials/filecoin/deploy-using-hardhat.md
> +#### Receive test Filecoin
Maybe "Receive test tokens"?

2023-01-17 13:31 UTC, soos3d commented on docs/tutorials/filecoin/deploy-using-hardhat.md
> +ERC-20 is the token implementation standard for smart contracts, and it defines a set of rules that a token contract must follow to be considered an ERC-20 token. These rules include how tokens are t
Good point, I'll make those changes.

2023-01-18 04:49 UTC, akegaviar commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
> +## Filecoin Virtual Machine and FIlecoin EVM
`FIlecoin` > `Filecoin`

2023-01-18 04:54 UTC, akegaviar commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
> +1. With Chainstack, create a [public chain project](https://docs.chainstack.com/glossary/public-chain-project).
remove blank lines in the ordered list.

also, here's a quick linter to find and fix all markdown issues inconsistencies

2023-01-18 04:55 UTC, akegaviar commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
> +### 1. Create a public chain project
No numbers in headers of step-by-step sections. Check other tutorials.

2023-01-18 04:59 UTC, akegaviar commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
> +
A new section should start here. eg call it `Check the deployed contract`

2023-01-18 14:13 UTC, conor2e requested changes
A few minor edits required.

2023-01-18 14:13 UTC, conor2e commented on docs/tutorials/filecoin/README.md
> +Learn how to develop and [deploy smart contracts on the Filecoin network using Hardhat](/tutorials/filecoin/deploy-using-hardhat).
Update the link to the new filename.

2023-01-18 14:13 UTC, conor2e commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
> +### 5. Create a simple ERC-20 token smart contract using the OpenZeppelin Contracts framework
Remove "5"

2023-01-18 14:13 UTC, conor2e commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
> +### 6. Deploy the contract on the Filecoin Hyperspace testnet through a node deployed with Chainstack
Remove "6"

2023-01-18 14:13 UTC, conor2e commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
> +This `0x1BEb36CF3de42a2c85d962bDE1517FFF136Bf0D1`, is a smart contract that we deployed. If you check on the [Hyperspace Filecoin explorer](https://hyperspace.filfox.info/en/address/t410fdpvtntz54qvc
Remove the comma after the smart contract number.

2023-01-18 14:29 UTC, ginstagram commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
> +The **Filecoin Ethereum Virtual Machine**, or FEVM brings the power of the Ethereum Virtual Machine (EVM) to the Filecoin network. The FEVM is virtualized as a runtime layer on top of the Filecoin Vi
Add a comma after "or FEVM"

2023-01-18 15:17 UTC, conor2e submitted a review, later dismissed
LGTM

2023-01-18 17:30 UTC, ginstagram commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
>  For yarn:
-> Capitalize "Yarn" when used as a product name outside code (as they do in their own docs)

2023-01-18 17:31 UTC, ginstagram commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
>  To create a Hardhat project, in your project's folder run:
Change "folder" to "directory" as per our style guide throughout

2023-01-18 17:40 UTC, ginstagram commented on docs/tutorials/filecoin/deploy-an-erc20-token-on-filecoin-with-hardhat.md
> +This `0x1BEb36CF3de42a2c85d962bDE1517FFF136Bf0D1` is a smart contract that we deployed. If you check on the [Hyperspace Filecoin explorer](https://hyperspace.filfox.info/en/address/t410fdpvtntz54qvcz
Word order for the explorer probably should be "Filecoin Hyperspace explorer"

2023-01-18 18:33 UTC, ginstagram approved these changes
LGTM 
Don't forget to add relnotes and change the version before merging.

2023-01-19 15:25 UTC, soos3d approved these changes
lgtm

2023-01-19 15:53 UTC, ginstagram commented on docs/release-notes.md
> +  * [Fliecoin](/operations/filecoin).
-> typo in Filecoin

2023-01-19 15:58 UTC, ginstagram approved these changes
LGTM

2023-01-19 16:03 UTC, soos3d approved these changes
lgtm

2023-01-19 16:13 UTC, closed without merging