5 Solana APIs now enabled
chainstack/docs pull request #581
Opened 2023-01-16 17:42 UTC by conor2e

## Description
5 heavy Solana APIs were enabled in ash1 and ams1 rate limited at 2RPS. Already implemented by dev so Nare requested doc updates asap. 

Only 5 APIs pages needed to have the Information note at the top updated.

Content reviewed and approved by PM Vladimir Feofilaktov in Slack. 

## Related Issue

https://chainstack.myjetbrains.com/youtrack/issue/DOCS-36/FVM-testnet-user-documentation

2023-01-16 17:44 UTC, conor2e commented
Needs version and release note updates.

2023-01-17 03:02 UTC, akegaviar requested changes
changes

2023-01-17 03:02 UTC, akegaviar commented on docs/api/solana/getmultipleaccounts.md
> +This method is now enabled for elastic Solana devnet nodes on US Ashborne (ash1) and Amsterdam (ams1) with a rate limit of 2 requests per second (RPS).
https://www.datacenters.com/amazon-aws-ashburn

2023-01-17 03:02 UTC, akegaviar commented on docs/api/solana/getmultipleaccounts.md
> +This method is now enabled for elastic Solana devnet nodes on US Ashborne (ash1) and Amsterdam (ams1) with a rate limit of 2 requests per second (RPS).
I don't think we should use `now` as there is no date here for anyone consuming this note. eg if two months, what would this `now` mean?

2023-01-17 04:08 UTC, easeev commented on docs/api/solana/getmultipleaccounts.md
> +This method is now enabled for elastic Solana devnet nodes on US Ashborne (ash1) and Amsterdam (ams1) with a rate limit of 2 requests per second (RPS).
In this case we're not hosted in AWS but I guess @akegaviar your point is Ashborne -> Ashburn

2023-01-17 11:41 UTC, ginstagram approved these changes
LGTM

2023-01-18 05:39 UTC, akegaviar approved these changes

2023-01-18 05:40 UTC, merged